source/api/urls.py
from django.urls import path

from api import views

app_name = 'api'

urlpatterns = [
    path('search', views.search.search_view, name="search"),
    # College
    path('buildings', views.college.BuildingList.as_view(), name="buildings"),
    path('places', views.college.PlaceList.as_view(), name="places"),
    path('rooms', views.college.RoomList.as_view(), name="rooms"),
    path('building/<int:building_id>/', views.college.Building.as_view(), name="building"),
    path('building/<int:building_id>/rooms', views.calendar.building_schedule_rooms_view,
         name="building_schedule_rooms"),
    path('building/<int:building_id>/schedule', views.calendar.building_schedule_shifts_view, name="building_schedule"),
    path('departments', views.college.DepartmentList.as_view(), name="departments"),
    path('department/<int:department_id>/', views.college.DepartmentDetailed.as_view(), name="department"),
    path('classes', views.college.ClassList.as_view(), name="classes"),
    path('courses', views.college.CoursesList.as_view(), name="courses"),
    path('course/<int:course_id>/', views.college.CourseDetailed.as_view(), name="course"),
    path('class/<int:class_id>/', views.college.Class.as_view(), name="class"),
    path('class/i/<int:instance_id>/', views.college.ClassInstance.as_view(), name="class_instance"),
    path('class/i/<int:instance_id>/shifts', views.college.ClassInstanceShifts.as_view(),
         name="class_instance_shifts"),
    path('class/i/<int:instance_id>/files', views.college.ClassFiles.as_view(), name="class_instance_files"),
    path('class/i/<int:instance_id>/schedule', views.calendar.class_instance_schedule, name="class_instance_schedule"),
    path('shift/<int:shift_id>', views.college.Shift.as_view(), name="shift"),
    path('enrollment/<int:enrollment_id>', views.college.Enrollment.as_view(), name="enrollment"),
    path('teacher/<int:teacher_id>/', views.college.Teacher.as_view(), name="teacher"),
    path('student/<int:student_id>/', views.college.Student.as_view(), name="student"),
    path('teacher/<int:teacher_id>/schedule', views.calendar.teacher_schedule, name="teacher_schedule"),

    # Chat
    # path('chat/list', views.chat.chat_list, name='chat_list'),
    path('chat/presence', views.chat.chat_presence, name='chat_presence'),
    path('chat/query', views.chat.chat_query, name='chat_query'),
    path('chat/<int:chat_id>/info', views.chat.chat_info, name='chat_info'),
    path('chat/<str:reference>/join', views.chat.chat_join_request, name='chat_join'),
    path('chat/<int:chat_id>/history', views.chat.chat_history, name='chat_history'),
    path('chat/<int:user_id>/dmrequest', views.chat.dm_request, name='chat_dm_request'),
    # Groups
    path('groups/', views.groups.GroupList.as_view(), name="groups"),
    path('group/<int:group_id>/', views.groups.Group.as_view(), name="group_activities"),
    path('group/<str:abbr>/calendar', views.calendar.group_calendar, name='group_calendar'),
    path('group/<str:abbr>/subscribe', views.groups.GroupSubscription.as_view(), name='group_subscription'),
    path('group/<str:abbr>/membership', views.groups.GroupMembershipRequest.as_view(), name='group_membership_request'),
    # News
    path('news/', views.news.NewsList.as_view(), name="news"),
    path('news/<int:pk>/', views.news.News.as_view(), name="news_item"),
    # Services
    path('services/', views.services.ServiceList.as_view(), name="services"),
    path('bars/', views.services.BarList.as_view(), name="services_bars"),
    path('transportation/day', views.third_party.transportation_day, name="transportation_day"),
    path('transportation/next', views.third_party.transportation_upcoming, name="transportation_upcoming"),
    path('weather/', views.third_party.weather, name="weather"),
    path('weather/chart/', views.third_party.weather_chart, name="weather_chart"),
    path('boinc/', views.third_party.boinc_view, name="boinc"),
    path('boinc/users/', views.third_party.boinc_users, name="boinc_users"),
    path('boinc/projects/', views.third_party.boinc_projects, name="boinc_projects"),
    path('stars/gitlab/', views.third_party.gitlab_stars, name="gitlab_stars"),
    path('stars/github/', views.third_party.github_stars, name="github_stars"),
    # Synopses
    path('learning/areas', views.learning.Areas.as_view(), name="synopses_areas"),
    path('learning/area/<int:pk>/', views.learning.Area.as_view(), name="synopses_area"),
    path('learning/subarea/<int:pk>/', views.learning.Subarea.as_view(), name="synopses_subarea"),
    path('learning/class/<int:pk>/children/', views.learning.ClassSections.as_view(),
         name='synopses_class_section'),
    path('learning/section/<int:pk>/', views.learning.Section.as_view(), name="synopses_section"),
    path('learning/section/<int:pk>/children/', views.learning.SectionChildren.as_view(),
         name='synopses_section_children'),
    path('learning/postable/<int:pk>/votes', views.learning.PostableVotes.as_view(), name="postable_votes"),
    path('learning/question/<int:pk>/votes', views.learning.QuestionUserVotes.as_view(), name="question_votes"),
    # Users
    path('login', views.users.Login.as_view(), name="user_login"),
    path('logout', views.users.Logout.as_view(), name="user_logout"),
    path('validation', views.users.ValidateToken.as_view(), name="user_validate"),
    path('profile/<str:nickname>/', views.users.ProfileDetailed.as_view(), name="user_profile"),
    path('profile/<str:nickname>/external_pages', views.users.UserExternalPages.as_view(), name='user_external_pages'),
    path('user/<str:nickname>/current_shifts', views.college.UserShiftInstances.as_view()),
    path('user/<str:nickname>/calendar', views.calendar.user_calendar, name='user_calendar'),
    path('user/<str:nickname>/schedule', views.calendar.user_schedule, name='user_schedule'),
    path('notification/count', views.users.notification_count_view, name='notification_count'),
    path('notification/list', views.users.UserNotificationList.as_view(), name='notification_list'),
    path('moderate/<int:user_id>/', views.users.UserModeration.as_view(), name='user_moderation'),
]

source/management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('users/', views.users_view, name='users'),
    path('activity/', views.activity_view, name='activity'),
    path('announcements/', views.announcements_view, name='announcements'),
    path('settings/', views.settings_view, name='settings'),
]

source/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('<str:nickname>/', views.profile_view, name='profile'),
    path('<str:nickname>/horario/', views.user_schedule_view, name='schedule'),
    path('<str:nickname>/calendario/', views.user_calendar_view, name='calendar'),
    path('<str:nickname>/calendario/editar', views.user_calendar_management_view, name='calendar_manage'),
    path('<str:nickname>/reputacao/', views.user_reputation_view, name='reputation'),
    path('<str:nickname>/avaliações/', views.user_evaluations_view, name='evaluations'),
    path('<str:nickname>/definicoes/', views.user_profile_settings_view, name='settings'),
    path('<str:nickname>/convites/', views.invites_view, name='invites'),
    path('<str:nickname>/convites/novo', views.create_invite_view, name='create_invite'),
    path('notificacoes', views.notifications_view, name='notifications'),
    path('ac/nickname/', views.NicknameAutocomplete.as_view(), name='nickname_ac'),
]

source/management/forms.py
from dal import autocomplete
from django import forms as djf
from django.core.exceptions import ValidationError

from supernova import models as supernova
from users import models as users, triggers
from college import models as college
from users.registrations import generate_token


class ChangelogForm(djf.ModelForm):
    broadcast_notification = djf.BooleanField(required=False)

    class Meta:
        model = supernova.Changelog
        fields = '__all__'


class ReputationOffsetForm(djf.ModelForm):
    class Meta:
        model = users.ReputationOffset
        fields = ('receiver', 'amount', 'reason')
        widgets = {'receiver': autocomplete.ModelSelect2(url='users:nickname_ac')}


class BindStudentToUserForm(djf.Form):
    user = djf.IntegerField(widget=autocomplete.Select2(url='users:nickname_ac'))
    student = djf.IntegerField(widget=autocomplete.Select2(url='college:unreg_student_ac'))

    def clean_user(self):
        user_id = self.cleaned_data.get("user")
        return users.User.objects.filter(id=user_id).first()

    def clean_student(self):
        student_id = self.cleaned_data.get("student")
        return college.Student.objects.filter(id=student_id, user=None).first()

    def save(self):
        user: users.User = self.cleaned_data.get('user')
        student: college.Student = self.cleaned_data.get('student')
        if student.user is None:
            triggers.student_assignment(user, student)
        else:
            raise ValidationError(f"Student {student.name} is already assigned to user {student.user.nickname}")


class BindTeacherToUserForm(djf.Form):
    user = djf.IntegerField(widget=autocomplete.Select2(url='users:nickname_ac'))
    teacher = djf.IntegerField(widget=autocomplete.Select2(url='college:unreg_teacher_ac'))

    def clean_user(self):
        user_id = self.cleaned_data.get("user")
        return users.User.objects.filter(id=user_id).first()

    def clean_teacher(self):
        teacher_id = self.cleaned_data.get("teacher")
        return college.Teacher.objects.filter(id=teacher_id, user=None).first()

    def save(self):
        user: users.User = self.cleaned_data.get('user')
        teacher: college.Teacher = self.cleaned_data.get('teacher')
        if teacher.user is None:
            triggers.teacher_assignment(user, teacher)
        else:
            raise ValidationError(f"Teacher {teacher.name} is already assigned to user {teacher.user.nickname}")


class PasswordResetForm(djf.Form):
    user = djf.IntegerField(widget=autocomplete.Select2(url='users:nickname_ac'))

    def clean_user(self):
        user_id = self.cleaned_data.get("user")
        return users.User.objects.filter(id=user_id).first()

    def save(self):
        user: users.User = self.cleaned_data.get('user')
        new_password = generate_token(length=10)
        user.set_password(new_password)
        user.save()
        return new_password

source/api/views/users.py
from datetime import datetime

from django.contrib.auth.hashers import check_password
from django.utils import timezone
from django.core.cache import cache
from rest_framework.authtoken.models import Token

from rest_framework.decorators import api_view, permission_classes
from rest_framework.exceptions import ParseError, ValidationError, PermissionDenied, AuthenticationFailed
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.generics import get_object_or_404

from api.serializers import users as serializers
from api import permissions
from users import models as users


@api_view(['GET'])
def chat_info(request, chat_id):
    conversation = get_object_or_404(chat.Conversation.instance_of(*LIVE_CONVERSATIONS), id=chat_id)
    if not conversation.has_access(request.user):
        raise PermissionDenied()
    serialized = serializers.ConversationSerializer(conversation)
    return Response(serialized.data)


class Login(APIView):

    def post(self, request):
        if not ('username' in request.data
                and isinstance(request.data['username'], str)
                and 'password' in request.data
                and isinstance(request.data['password'], str)):
            raise ParseError()

        target_user = get_object_or_404(users.User.objects, username=request.data['username'])
        if target_user.check_password(request.data['password']):
            token = Token.objects.create(user=target_user)
            return Response({'token': token.key})
        else:
            raise AuthenticationFailed()

class Logout(APIView):
    permission_classes = (IsAuthenticated,)

    def delete(self, request):
        request.auth.delete()
        return Response("Success")



class ValidateToken(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        # DRF does everything by default
        return Response("Success")


class ProfileDetailed(APIView):
    permission_classes = (permissions.SelfOnly,)

    def get(self, request, nickname):  # TODO authentication
        user = get_object_or_404(users.User, nickname=nickname)
        serializer = serializers.ProfileDetailedSerializer(user)
        return Response(serializer.data)


class UserExternalPages(APIView):
    permission_classes = (permissions.SelfOnly,)

    def get(self, request, nickname):  # TODO restrict to privacy level
        user = get_object_or_404(users.User, nickname=nickname)
        serializer = serializers.ExternalPageSerializer(user.external_pages, many=True)
        return Response(serializer.data)

    def put(self, request, nickname):  # TODO restrict to owner
        user = get_object_or_404(users.User, nickname=nickname)
        if 'url' not in request.data:
            raise Response(status=400)

        page = users.ExternalPage.objects.create(user=user, url=request.data['url'])
        serializer = serializers.ExternalPageSerializer(page)
        return Response(serializer.data)

    def delete(self, request, nickname):
        user = get_object_or_404(users.User, nickname=nickname)
        if 'id' not in request.data:
            raise Response(status=400)
        page = get_object_or_404(users.ExternalPage, id=request.data['id'], user=user)
        page.delete()
        return Response()


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def notification_count_view(request):
    notification_count = cache.get('%s_notification_count' % request.user.id)
    if notification_count is None:
        count = users.Notification.objects.filter(receiver=request.user, dismissed=False).count()
        cache.set('%s_notification_count' % request.user.nickname, count)
        return Response(count)
    return Response(notification_count)


class UserNotificationList(APIView):

    def get(self, request):
        timestamp = int(datetime.now().replace(tzinfo=timezone.utc).timestamp())
        notification_list = cache.get('%s_notification_list' % request.user.id)
        if notification_list is None:
            notifications = users.Notification.objects \
                .filter(receiver=request.user, dismissed=False) \
                .order_by('issue_timestamp') \
                .reverse()
            notification_list = list(map(lambda n: n.to_api(), notifications))
            cache.set('%s_notification_list' % request.user.id, notification_list)
        return Response({'notifications': notification_list, 'timestamp': timestamp})

    def delete(self, request):
        if 'timestamp' in request.data:
            timestamp = timezone.make_aware(datetime.fromtimestamp(request.data['timestamp']))
            users.Notification.objects \
                .filter(receiver=request.user, issue_timestamp__lte=timestamp) \
                .update(dismissed=True)
        else:
            users.Notification.objects.filter(receiver=request.user).update(dismissed=True)
        request.user.clear_notification_cache()
        return Response()


class UserModeration(APIView):
    permission_classes = (IsAdminUser,)

    def get(self, request, user_id, format=None):
        user = users.User.objects.get(id=user_id)
        return Response({'active': user.is_active})

    def post(self, request, user_id, format=None):
        user = users.User.objects.get(id=user_id)
        if user.is_staff:
            raise PermissionDenied("Cannot take actions against administrators")
        if not (isinstance(request.data, dict) and 'action' in request.data):
            raise ParseError()
        action = request.data['action']
        if action == 'suspend':
            user.is_active = False
        elif action == 'unsuspend':
            user.is_active = True
        user.save()
        return Response("Ok")

source/management/templates/management/activity.html
{% extends 'supernova/base.html' %}

{% load static %}

{% block content_wrapper %}
  <div class="col padded">
    <div class="pane">
      <div class="pane-title"><h2>Actividade</h2></div>
      <div class="pane-content">
        <table>
          <tr>
            <th>Data</th>
            <th>Utilizador</th>
            <th>Descrição</th>
          </tr>
          {% for activity in latest_activity %}
            <tr>
              <td>{{ activity.timestamp|date:'d/m/Y H:i' }}</td>
              <td><a href="{% url 'users:profile' activity.user.nickname %}">{{ activity.user.nickname }}</a></td>
              <td>{{ activity|capfirst }}</td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
{% endblock %}

source/management/templates/management/announcements.html
{% extends 'supernova/base.html' %}

{% load static %}

{% block head %}
  <link href="{% static  'vendor/select2/dist/css/select2.min.css' %}" type="text/css" media="screen" rel="stylesheet">
  <link href="{% static  'admin/css/autocomplete.css' %}" type="text/css" media="screen" rel="stylesheet">
  <link href="{% static  'autocomplete_light/select2.css' %}" type="text/css" media="screen" rel="stylesheet">
  <script src="{% static  'autocomplete_light/jquery.init.js' %}"></script>
  <script src="{% static  'vendor/select2/dist/js/select2.full.min.js' %}"></script>
  <script src="{% static  'vendor/select2/dist/js/i18n/pt.js' %}"></script>
  <script src="{% static  'autocomplete_light/autocomplete.init.js' %}"></script>
  <script src="{% static  'autocomplete_light/forward.js' %}"></script>
  <script src="{% static  'autocomplete_light/select2.js' %}"></script>
  <script src="{% static  'autocomplete_light/jquery.post-setup.js' %}"></script>
{% endblock %}

{% block content_wrapper %}
  <div class="col padded">
    <div class="pane">
      <div class="pane-title"><h2>Anúnciar alteração</h2></div>
      <div class="pane-content">
        <form method="post" action="{% url 'management:announcements' %}?announce=">
          {% csrf_token %}
          {{ changelog_form.as_p }}
          <input style="float: right" type="submit" value="Anúnciar">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

source/management/templates/management/index.html
{% extends 'supernova/base.html' %}

{% load static %}

{% block content_wrapper %}
  {% csrf_token %}
  <div class="row padded">
    <div class="col">
      <div class="pane">
        <div class="pane-title"><h2>-</h2></div>
        <div class="pane-content">
        </div>
      </div>
    </div>
  </div>
{% endblock %}

source/management/templates/management/settings.html
{% extends 'supernova/base.html' %}

{% load static %}

{% block content_wrapper %}
    <div class="col">
      <div class="pane">
        <div class="pane-title"><h2>Definições</h2></div>
        <div class="pane-content">
        </div>
      </div>
    </div>
{% endblock %}

source/management/templates/management/users.html
{% extends 'supernova/base.html' %}

{% load static %}

{% block head %}
  <script src="{% static  'management/users.js' %}"></script>
  <link href="{% static  'vendor/select2/dist/css/select2.min.css' %}" type="text/css" media="screen" rel="stylesheet">
  <link href="{% static  'admin/css/autocomplete.css' %}" type="text/css" media="screen" rel="stylesheet">
  <link href="{% static  'autocomplete_light/select2.css' %}" type="text/css" media="screen" rel="stylesheet">
  <script src="{% static  'autocomplete_light/jquery.init.js' %}"></script>
  <script src="{% static  'vendor/select2/dist/js/select2.full.min.js' %}"></script>
  <script src="{% static  'vendor/select2/dist/js/i18n/pt.js' %}"></script>
  <script src="{% static  'autocomplete_light/autocomplete.init.js' %}"></script>
  <script src="{% static  'autocomplete_light/forward.js' %}"></script>
  <script src="{% static  'autocomplete_light/select2.js' %}"></script>
  <script src="{% static  'autocomplete_light/jquery.post-setup.js' %}"></script>
{% endblock %}

{% block content_wrapper %}
  {% csrf_token %}
  <div class="row padded">
    <div class="col">
      <div class="pane">
        <div class="pane-title"><h2>Últimos registos</h2></div>
        <div class="pane-content">
          <table class="stylized grow">
            <tr>
              <th>Username</th>
              <th>Alcunha</th>
              <th>Estudante</th>
              <th>Professor</th>
              <th>Email</th>
              <th>F</th>
              <th>Convidante</th>
              <th>Data</th>
            </tr>
            {% for registration in latest_registrations %}
              <tr>
                <td>
                  {% if registration.resulting_user %}
                    <a href="{{ registration.resulting_user.get_absolute_url }}">{{ registration.username }}</a>
                  {% else %}
                    {{ registration.username }}
                  {% endif %}
                </td>
                <td>{% if registration.nickname and registration.nickname != '' %}{{ registration.nickname }}{% else %}-{% endif %}</td>
                <td>{{ registration.requested_student.abbreviation }}</td>
                <td>{% if registration.requested_teacher %}<a href="{{ registration.requested_teacher.get_absolute_url }}">Link</a>{% endif %}</td>
                <td>{{ registration.email|cut:"campus.fct.unl.pt" }}</td>
                <td>{{ registration.failed_attempts }}</td>
                <td>{% if registration.invite %}<a href="{{ registration.invite.issuer.get_absolute_url }}">{{ registration.invite.issuer.nickname }}</a>{% else %} - {% endif %}</td>
                <td>{{ registration.creation|date:'Y/m/d H:i' }}</td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Atribuições docentes pendentes</h2></div>
        <div class="pane-content">
          <table class="stylized grow">
            <tr>
              <th>Username</th>
              <th>Alcunha</th>
              <th>Professor</th>
              <th>Email</th>
              <th>Data</th>
            </tr>
            {% for registration in registrations_with_claimed_teachers %}
              <tr>
                <td>
                  {% if registration.resulting_user %}
                    <a href="{{ registration.resulting_user.get_absolute_url }}">{{ registration.username }}</a>
                  {% else %}
                    {{ registration.username }}
                  {% endif %}
                </td>
                <td>
                  {% if registration.nickname and registration.nickname != '' %}
                    {{ registration.nickname }}
                  {% else %}-{% endif %}
                </td>
                <td>
                  {% if registration.requested_teacher %}
                    <a href="{{ registration.requested_teacher.get_absolute_url }}">
                      {{ registration.requested_teacher.name }}
                    </a>
                  {% endif %}
                </td>
                <td>{{ registration.email|cut:"fct.unl.pt" }}</td>
                <td>{{ registration.creation|date:'Y/m/d H:i' }}</td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Utilizadores</h2></div>
        <div class="pane-content stylized grow">
          <table class="stylized grow">
            <thead>
            <tr>
              <th>Username</th>
              <th>Alcunha</th>
              <th>Points</th>
            </tr>
            </thead>
            <tbody>
            {% for other_user in users %}
              <tr>
                <td>{{ other_user.username }}</td>
                <td><a href="{{ other_user.get_absolute_url }}">{{ other_user.nickname }}</a></td>
                <td>{{ other_user.points }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="pane">
        <div class="pane-title"><h2>Utilizadores suspensos</h2></div>
        <div class="pane-content" data-endpoint="{% url 'api:user_moderation' 0 %}">
          {% if suspended_users|length == 0 %}
            Sem utilizadores suspensos.
          {% else %}
            <table>
              <tr>
                <th>Utilizador</th>
                <th>Até</th>
                <th></th>
              </tr>
              {% for user in suspended_users %}
                <tr data-id="{{ user.id }}">
                  <td><a href="{% url 'users:profile' user.nickname %}">{{ user.nickname }}</a></td>
                  <td>-</td>
                  <td><a onclick="removeSuspension(this, {{ user.id }})">Anular</a></td>
                </tr>
              {% endfor %}
            </table>
          {% endif %}
          <h4>Suspender:</h4>
          <select name="section" required id="suspension-selector" data-autocomplete-light-url="/u/ac/nickname/"
                  data-autocomplete-light-function="select2"></select>
          <input type="button" value="Confirmar" onclick="suspend()">
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Emitir diferencial de pontos</h2></div>
        <div class="pane-content">
          <form class="col" method="post" action="{% url 'management:users' %}?reputation_offset=">
            {% csrf_token %}
            {{ reputation_offset_form.as_p }}
            <input class="ui-btn end" type="submit" value="Emitir">
          </form>
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Atribuir professor</h2></div>
        <div class="pane-content">
          <form class="col" method="post" action="{% url 'management:users' %}?assign_teacher=">
            {% csrf_token %}
            {{ assign_teacher_form.as_p }}
            <input class="ui-btn end" type="submit" value="Atribuir">
          </form>
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Atribuir aluno</h2></div>
        <div class="pane-content">
          <form class="col" method="post" action="{% url 'management:users' %}?assign_student=">
            {% csrf_token %}
            {{ assign_student_form.as_p }}
            <input class="ui-btn end" type="submit" value="Atribuir">
          </form>
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Alterar password</h2></div>
        <div class="pane-content">
          <form class="col" method="post" action="{% url 'management:users' %}?password_reset=">
            {% csrf_token %}
            {% if new_password %}
              Password gerada: <b>{{ new_password }}</b>
            {% else %}
              {{ password_reset_form.as_p }}
              <input class="ui-btn end" type="submit" value="Gerar nova">
            {% endif %}
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}