source/api/urls.py
from django.urls import path

from api import views

app_name = 'api'

urlpatterns = [
    path('search', views.search.search_view, name="search"),
    # College
    path('buildings', views.college.BuildingList.as_view(), name="buildings"),
    path('places', views.college.PlaceList.as_view(), name="places"),
    path('rooms', views.college.RoomList.as_view(), name="rooms"),
    path('building/<int:building_id>/', views.college.Building.as_view(), name="building"),
    path('building/<int:building_id>/rooms', views.calendar.building_schedule_rooms_view,
         name="building_schedule_rooms"),
    path('building/<int:building_id>/schedule', views.calendar.building_schedule_shifts_view, name="building_schedule"),
    path('departments', views.college.DepartmentList.as_view(), name="departments"),
    path('department/<int:department_id>/', views.college.DepartmentDetailed.as_view(), name="department"),
    path('classes', views.college.ClassList.as_view(), name="classes"),
    path('courses', views.college.CoursesList.as_view(), name="courses"),
    path('course/<int:course_id>/', views.college.CourseDetailed.as_view(), name="course"),
    path('class/<int:class_id>/', views.college.Class.as_view(), name="class"),
    path('class/i/<int:instance_id>/', views.college.ClassInstance.as_view(), name="class_instance"),
    path('class/i/<int:instance_id>/shifts', views.college.ClassInstanceShifts.as_view(),
         name="class_instance_shifts"),
    path('class/i/<int:instance_id>/files', views.college.ClassFiles.as_view(), name="class_instance_files"),
    path('class/i/<int:instance_id>/schedule', views.calendar.class_instance_schedule, name="class_instance_schedule"),
    path('shift/<int:shift_id>', views.college.Shift.as_view(), name="shift"),
    path('enrollment/<int:enrollment_id>', views.college.Enrollment.as_view(), name="enrollment"),
    path('teacher/<int:teacher_id>/', views.college.Teacher.as_view(), name="teacher"),
    path('student/<int:student_id>/', views.college.Student.as_view(), name="student"),
    path('teacher/<int:teacher_id>/schedule', views.calendar.teacher_schedule, name="teacher_schedule"),

    # Chat
    # path('chat/list', views.chat.chat_list, name='chat_list'),
    path('chat/presence', views.chat.chat_presence, name='chat_presence'),
    path('chat/query', views.chat.chat_query, name='chat_query'),
    path('chat/<int:chat_id>/info', views.chat.chat_info, name='chat_info'),
    path('chat/<str:reference>/join', views.chat.chat_join_request, name='chat_join'),
    path('chat/<int:chat_id>/history', views.chat.chat_history, name='chat_history'),
    path('chat/<int:user_id>/dmrequest', views.chat.dm_request, name='chat_dm_request'),
    # Groups
    path('groups/', views.groups.GroupList.as_view(), name="groups"),
    path('group/<int:group_id>/', views.groups.Group.as_view(), name="group_activities"),
    path('group/<str:abbr>/calendar', views.calendar.group_calendar, name='group_calendar'),
    path('group/<str:abbr>/subscribe', views.groups.GroupSubscription.as_view(), name='group_subscription'),
    path('group/<str:abbr>/membership', views.groups.GroupMembershipRequest.as_view(), name='group_membership_request'),
    # News
    path('news/', views.news.NewsList.as_view(), name="news"),
    path('news/<int:pk>/', views.news.News.as_view(), name="news_item"),
    # Services
    path('services/', views.services.ServiceList.as_view(), name="services"),
    path('bars/', views.services.BarList.as_view(), name="services_bars"),
    path('transportation/day', views.third_party.transportation_day, name="transportation_day"),
    path('transportation/next', views.third_party.transportation_upcoming, name="transportation_upcoming"),
    path('weather/', views.third_party.weather, name="weather"),
    path('weather/chart/', views.third_party.weather_chart, name="weather_chart"),
    path('boinc/', views.third_party.boinc_view, name="boinc"),
    path('boinc/users/', views.third_party.boinc_users, name="boinc_users"),
    path('boinc/projects/', views.third_party.boinc_projects, name="boinc_projects"),
    path('stars/gitlab/', views.third_party.gitlab_stars, name="gitlab_stars"),
    path('stars/github/', views.third_party.github_stars, name="github_stars"),
    # Synopses
    path('learning/areas', views.learning.Areas.as_view(), name="synopses_areas"),
    path('learning/area/<int:pk>/', views.learning.Area.as_view(), name="synopses_area"),
    path('learning/subarea/<int:pk>/', views.learning.Subarea.as_view(), name="synopses_subarea"),
    path('learning/class/<int:pk>/children/', views.learning.ClassSections.as_view(),
         name='synopses_class_section'),
    path('learning/section/<int:pk>/', views.learning.Section.as_view(), name="synopses_section"),
    path('learning/section/<int:pk>/children/', views.learning.SectionChildren.as_view(),
         name='synopses_section_children'),
    path('learning/postable/<int:pk>/votes', views.learning.PostableVotes.as_view(), name="postable_votes"),
    path('learning/question/<int:pk>/votes', views.learning.QuestionUserVotes.as_view(), name="question_votes"),
    # Users
    path('login', views.users.Login.as_view(), name="user_login"),
    path('logout', views.users.Logout.as_view(), name="user_logout"),
    path('validation', views.users.ValidateToken.as_view(), name="user_validate"),
    path('profile/<str:nickname>/', views.users.ProfileDetailed.as_view(), name="user_profile"),
    path('profile/<str:nickname>/external_pages', views.users.UserExternalPages.as_view(), name='user_external_pages'),
    path('user/<str:nickname>/current_shifts', views.college.UserShiftInstances.as_view()),
    path('user/<str:nickname>/calendar', views.calendar.user_calendar, name='user_calendar'),
    path('user/<str:nickname>/schedule', views.calendar.user_schedule, name='user_schedule'),
    path('notification/count', views.users.notification_count_view, name='notification_count'),
    path('notification/list', views.users.UserNotificationList.as_view(), name='notification_list'),
    path('moderate/<int:user_id>/', views.users.UserModeration.as_view(), name='user_moderation'),
]

source/groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('nucleos', views.nuclei_view, name='nuclei'),
    path('institucionais', views.institutional_view, name='institutional'),
    path('pedagogicos', views.pedagogic_view, name='pedagogic'),
    path('comunidades', views.communities_view, name='communities'),
    path('<str:group_abbr>', views.group_view, name='group'),
    path('<str:group_abbr>/documentos', views.documents_view, name='documents'),
    path('<str:group_abbr>/anuncios', views.announcements_view, name='announcements'),
    path('<str:group_abbr>/membros', views.members_view, name='members'),
    path('<str:group_abbr>/admissao', views.group_membership_request_view, name='membership_req'),
    path('<str:group_abbr>/candidaturas', views.group_candidates_view, name='candidates'),
    path('<str:group_abbr>/definicoes', views.settings_view, name='settings'),
    path('<str:group_abbr>/cargos', views.roles_view, name='roles'),
    path('<str:group_abbr>/cargo/<int:role_id>', views.role_view, name='role'),
    path('<str:group_abbr>/anunciar', views.announce_view, name='announce'),
    path('<str:group_abbr>/anuncio/<str:announcement_id>', views.announcement_view, name='announcement'),
    path('<str:group_abbr>/agendar', views.calendar_management_view, name='calendar_manage'),
    path('<str:group_abbr>/conversas', views.conversations_view, name='conversations'),
    path('<str:group_abbr>/conversas/criar', views.conversation_create_view, name='conversation_create'),
    path('<str:group_abbr>/conversas/<str:conversation_id>', views.conversation_view, name='conversation'),
    path('ac/group_role', views.GroupRolesAutocomplete.as_view(), name='group_role_ac'),
]

source/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('<str:nickname>/', views.profile_view, name='profile'),
    path('<str:nickname>/horario/', views.user_schedule_view, name='schedule'),
    path('<str:nickname>/calendario/', views.user_calendar_view, name='calendar'),
    path('<str:nickname>/calendario/editar', views.user_calendar_management_view, name='calendar_manage'),
    path('<str:nickname>/reputacao/', views.user_reputation_view, name='reputation'),
    path('<str:nickname>/avaliações/', views.user_evaluations_view, name='evaluations'),
    path('<str:nickname>/definicoes/', views.user_profile_settings_view, name='settings'),
    path('<str:nickname>/convites/', views.invites_view, name='invites'),
    path('<str:nickname>/convites/novo', views.create_invite_view, name='create_invite'),
    path('notificacoes', views.notifications_view, name='notifications'),
    path('ac/nickname/', views.NicknameAutocomplete.as_view(), name='nickname_ac'),
]

source/documents/models.py
from django.conf import settings
from django.db import models as djm

from college.models import Place, Building
from groups.models import Group


class Document(djm.Model):
    author_user = djm.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=djm.SET_NULL,
        related_name='document_author')
    author_group = djm.ForeignKey(Group, null=True, blank=True, on_delete=djm.SET_NULL)
    title = djm.CharField(max_length=256)
    content = djm.TextField()
    creation = djm.DateField(auto_now_add=True)
    public = djm.BooleanField(default=False)
    last_edition = djm.DateTimeField(null=True, blank=True, default=None)
    last_editor = djm.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        default=None,
        on_delete=djm.SET_NULL,
        related_name='document_editor')

    class Meta:
        ordering = ['creation']

    def __str__(self):
        return f'{self.title}, {self.author_user}'


class UserPermission(djm.Model):
    document = djm.ForeignKey(Document, on_delete=djm.CASCADE)
    user = djm.ForeignKey(settings.AUTH_USER_MODEL, on_delete=djm.CASCADE)


class GroupPermission(djm.Model):
    document = djm.ForeignKey(Document, on_delete=djm.CASCADE)
    group = djm.ForeignKey(Group, on_delete=djm.CASCADE)

source/api/views/groups.py
from django.db import IntegrityError
from rest_framework import generics
from rest_framework.generics import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from api.serializers import groups as serializers
from groups import models as m
from users import models as users


class GroupList(APIView):
    def get(self, request, format=None):
        serializer = serializers.GroupSerializer(m.Group.objects.all(), many=True)
        return Response(serializer.data)


class Group(APIView):
    def get(self, request, group_id=None):
        serializer = serializers.RelatedGroupSerializer(m.Group.objects.get(id=group_id))
        return Response(serializer.data)


class GroupSubscription(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, abbr):
        group = get_object_or_404(m.Group, abbreviation=abbr)
        is_subscribed = users.Subscription.objects.filter(group=group, subscriber=request.user).exists()
        return Response(is_subscribed)

    def post(self, request, abbr):
        group = get_object_or_404(m.Group, abbreviation=abbr)
        is_subscribed = users.Subscription.objects.filter(group=group, subscriber=request.user).exists()
        if not is_subscribed:
            try:
                users.Subscription.objects.create(to=group, subscriber=request.user)
            except IntegrityError:
                return Response(status=409)
        return Response()

    def delete(self, request, abbr):
        group = get_object_or_404(m.Group, abbreviation=abbr)
        users.Subscription.objects.filter(group=group, subscriber=request.user).delete()
        return Response()


class GroupMembershipRequest(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, abbr):
        group = get_object_or_404(m.Group, abbreviation=abbr)
        openness = group.outsiders_openness
        if group.outsiders_openness == m.Group.REQUEST:
            has_requested = m.MembershipRequest.objects.filter(group=group, user=request.user).exists()
        else:
            has_requested = False
        return Response({'openness': openness, 'requested': has_requested})

    def post(self, request, abbr):
        group = get_object_or_404(m.Group, abbreviation=abbr)
        if m.Membership.objects.filter(member=request.user, group=group).exists():
            raise Response("Membership already exists", status=409)

        if group.outsiders_openness == m.Group.OPEN:
            if group.default_role_id is None:
                raise Response("Group has no default role", status=502)
            else:
                m.Membership.objects.create(member=request.user, group=group, role_id=group.default_role_id)
                raise Response()
        elif group.outsiders_openness == m.Group.REQUEST:
            has_requested = m.MembershipRequest.objects.filter(group=group, user=request.user).exists()
            if has_requested:
                return Response(status=409)
            if 'message' in request.POST:
                message = request.POST['message']
                if isinstance(message, str):
                    message = message.strip()
                    m.MembershipRequest.objects.create(group=group, user=request.user, message=message)
                else:
                    return Response(status=400)
            m.MembershipRequest.objects.create(group=group, user=request.user)
        else:
            return Response("Group has restricted access", status=403)
        return Response()

    def delete(self, request, abbr):
        group = get_object_or_404(m.Group, abbreviation=abbr)
        # Only delete requests without a verdict
        m.MembershipRequest.objects.filter(group=group, user=request.user, granted=None).delete()
        return Response()

source/documents/views.py
from django.shortcuts import render, get_object_or_404

from documents.models import Document
from supernova.views import build_base_context


def document(request, document_id):
    context = build_base_context(request)
    document = get_object_or_404(Document, id=document_id)
    title = document.title
    context['title'] = title
    context['document'] = document
    context['sub_nav'] = [{'name': 'Documentos', 'url': '#'},
                          {'name': title, 'url': '#'}]
    return render(request, 'documents/document.html', context)

source/groups/templates/groups/announce.html
{% extends 'groups/base_simple.html' %}

{% load static %}

{% block head %}
  <script src="{% static 'js/content-rendering.js' %}"></script>
{% endblock %}

{% block group_content %}
  <div class="pane">
    <div class="pane-title"><h2>Anúnciar</h2></div>
    <div class="pane-content">
      <form class="col" method="post" action="{% url 'groups:announce' group.abbreviation %}">
        {% csrf_token %}
        {{ form.errors }}
        <div class="form-block">
          <div class="form-row">
            <div class="form-row-top">
              <h4>Título</h4>
            </div>
            {{ form.title }}
            <div class="form-row-description">
              Descrição <b>curta e clara</b> o suficiente para dar a entender do que se trata o conteúdo.<br>
              Poderá constar em locais espacialmente limitados (como numa notificação).
            </div>
          </div>
          <hr>
          <div class="form-row">
            <div class="form-row-top">
              <h4>Conteúdo</h4>
            </div>
            <div class="form-row-description">
              Informação anúnciar, verbosa se necessário.
            </div>
            {{ form.content }}
          </div>
        </div>
        <input class="ui-btn end" type="submit" value="Públicar"/>
        {{ form.media }}
      </form>
    </div>
  </div>
{% endblock %}

source/groups/templates/groups/announcement.html
{% extends 'groups/base_simple.html' %}

{% load static %}

{% block group_content %}
  <div class="pane">
    <div class="pane-title"><h2>{{ announcement.title }}</h2></div>
    <div class="pane-content">
      {{ announcement.content_html|safe }}
      <hr>
      Colocado em {{ announcement.datetime }} por
      <a href="{% url 'users:profile' announcement.author.nickname %}">{{ announcement.author.name }}</a>
    </div>
  </div>
{% endblock %}

source/groups/templates/groups/announcements.html
{% extends 'groups/base.html' %}

{% block group_content %}
  {% if not announcements.exists %}
    <div class="pane">
      <div class="pane-title"><h2>Anúncios</h2></div>
      <div class="pane-content">
        Este grupo nunca anunciou nada.<br>
        Talvez sejam tímidos, talvez não tenham presença no Supernova. :(
      </div>
    </div>
  {% endif %}
  {% for announcement in announcements %}
    <div class="pane">
      <div class="pane-title">
        <h2><a href="{% url 'groups:announcement' group.abbreviation announcement.id %}">{{ announcement.title }}</a></h2>
      </div>
      <div class="pane-content">
        {{ announcement.content_html | safe }}
      </div>
    </div>
  {% endfor %}
{% endblock %}

source/groups/templates/groups/base_simple.html
{% extends 'supernova/base.html' %}

{% block head %}
  {{ block.super }}
  {% include 'groups/group_cover_image.html' %}
{% endblock %}

{% block content_wrapper %}
  {% csrf_token %}
  <div class="col">
    {% include 'groups/header.html' %}
    <div class="col padded">
      {% block group_content %}{% endblock %}
    </div>
  </div>
{% endblock %}

source/groups/templates/groups/documents.html
{% extends 'groups/base.html' %}

{% block group_content %}
  <div class="pane">
    <div class="pane-title"><h2>Ficheiros</h2></div>
    <div class="pane-content">
      {% for document in documents %}
        <div>
          <h2><a href="{% url 'document' document.id %}">{{ document.title }}</a></h2>
          <span>Criado em {{ document.creation }} {% if document.author_user %}por
            <a href="{% url 'users:profile' document.author_user.nickname %}">{{ document.author_user }}</a> {% endif %}
            {% if document.last_edition %}<br>Última edição em {{ document.last_edition }} por
              {{ document.last_editor }}{% endif %}</span>
        </div>
      {% endfor %}
      {% if documents|length == 0 %}<span>Sem ficheiros partilhados</span>{% endif %}
    </div>
  </div>
{% endblock %}

source/groups/templates/groups/group_cover_image.html
{% if group.icon %}
  {% spaceless %}
    <style>
        .header-background:after {
            background-image: url("{{ group.icon_big.url}}");
        }
    </style>
  {% endspaceless %}
{% endif %}

source/groups/templates/groups/groups.html
{% extends 'supernova/content_only_formatted.html' %}

{% load static %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/balloon.min.css' %}"/>
  <style>
    .flex-grid-item {
      background-size: contain;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="flex-wrapper">
    {% for group in groups %}
      {% if not type_filter or group.type == type_filter %}
        <a href="{% url 'groups:group' group.abbreviation %}">
          <div class="flex-grid-item" {% if group.image %}style="background-image: url('{{ group.image_thumbnail.url }}')"{% endif %}>
            <div class="flex-grid-item-top">
              <span>{{ group.name }}</span>
            </div>
            <div class="flex-grid-item-bottom">
              {% if not group.official %}
                <div aria-label="Sem presença oficial." data-balloon-pos="up">
                  <img src="{% static 'img/icons/warning.svg' %}">
                </div>
              {% endif %}
              <div aria-label="Membros" data-balloon-pos="up">
                <img src="{% static 'img/icons/users.svg' %}">
                {{ group.members.count }}
              </div>
              {% if group.non_member_permission < group.OPEN %}
                <img src="{% static 'img/icons/locked.svg' %}">
              {% endif %}
            </div>
          </div>
        </a>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

source/groups/templates/groups/header.html
{% load static %}

{% if group.image %}<div class="header-background faded contain right">{% endif %}
<div class="header-decorator">
  <div class="header-decorator-options">
    <ul>
      {% for action in actions %}
        <li><a href="{{ action.url }}">{{ action.name }}</a></li>
      {% endfor %}
      {% if not user.is_anonymous %}
        <li><a id="subscribe-btn" href="javascript: void(0)" data-endpoint="{% url 'api:group_subscription' group.abbreviation %}"></a></li>
      {% endif %}
    </ul>
  </div>
  <div>
    <h1>{{ group.name }}</h1>
    {% if not group.official %}
      <span style="float: right">(<img src="{% static 'img/icons/warning.svg' %}" height="16px"> Não oficial)</span>
    {% endif %}
    <h3>@{{ group.abbreviation }}</h3>
  </div>
</div>
{% if group.image %}</div>{% endif %}
<script>setSubscribeButton();</script>

source/groups/templates/groups/navigation.html
{% url 'groups:group' group.abbreviation  as main_url %}
{% url 'groups:announcements' group.abbreviation  as announcements_url %}
{% url 'groups:documents' group.abbreviation  as documents_url %}
{% url 'groups:members' group.abbreviation  as members_url %}
{% url 'groups:conversations' group.abbreviation  as conversations_url %}

<div class="pane">
  <div class="pane-title"><h2>Páginas</h2></div>
  <div class="pane-content">
    <ul class="menu">
      {% if request.path == main_url %}
        <li>Página principal</li>
      {% else %}
        <li><a href="{{ main_url }}">Página principal</a></li>
      {% endif %}

      {% if request.path == announcements_url %}
        <li>Anúncios</li>
      {% else %}
        <li><a href="{{ announcements_url }}">Anúncios</a></li>
      {% endif %}

{#      {% if request.path == documents_url %} TODO#}
{#        <li>Documentos</li>#}
{#      {% else %}#}
{#        <li><a href="{{ documents_url }}">Documentos</a></li>#}
{#      {% endif %}#}

      {% if request.path == members_url %}
        <li>Membros</li>
      {% else %}
        <li><a href="{{ members_url }}">Membros</a></li>
      {% endif %}

      {% if request.path == conversations_url %}
        <li>Contactar</li>
      {% else %}
        <li><a href="{{ conversations_url }}">Contactar</a></li>
      {% endif %}
      {# TODO - Schedule, Calendar, Documents #}
    </ul>
  </div>
</div>

{% if is_member %}
  <div class="pane">
    <div class="pane-title"><h2>Administração</h2></div>
    <div class="pane-content">
      <ul class="menu">
        {% if  membership_perms.can_announce %}
          <li><a href="{% url 'groups:announce' group.abbreviation %}">Anúnciar</a></li>{% endif %}
        {% if  membership_perms.can_modify_roles %}
          <li><a href="{% url 'groups:roles' group.abbreviation %}">Gerir cargos</a></li>{% endif %}
        {% if  membership_perms.can_modify_roles %}
          <li><a href="{% url 'groups:candidates' group.abbreviation %}">Analisar candidaturas</a></li>{% endif %}
        {% if  membership_perms.can_change_schedule %}
          <li><a href="{% url 'groups:calendar_manage' group.abbreviation %}">Alterar agenda</a></li>{% endif %}
        {% if  membership_perms.is_admin %}
          <li><a href="{% url 'groups:settings' group.abbreviation %}">Definições</a></li>{% endif %}
      </ul>
    </div>
  </div>
{% endif %}

source/groups/templates/groups/roles.html
{% extends 'groups/base_simple.html' %}

{% load static %}

{% block head %}
  {{ block.super }}
  <style>
      th {
          background-color: var(--bg2);
          padding: 2px;
      }

      td {
          text-align: center;
      }

      td img {
          width: 24px;
      }
  </style>
{% endblock %}

{% block group_content %}
  <div class="pane">
    <div class="pane-title"><h2>Cargos</h2></div>
    <div class="pane-content col">
      <div style="overflow: auto">
        <table class="stylized grow">
          <tr>
            <th rowspan="2">Nome</th>
            <th colspan="2">Cargos</th>
            <th rowspan="2">Anuncia</th>
            <th colspan="2">Chat</th>
            <th colspan="2">Chat Interno</th>
            <th colspan="3">Documentos</th>
            <th rowspan="2">Edita horários</th>
          </tr>
          <tr>
            <th>Modifica</th>
            <th>Atribui</th>
            <th>Lê</th>
            <th>Escreve</th>
            <th>Lê</th>
            <th>Escreve</th>
            <th>Lê privados</th>
            <th>Escreve privados</th>
            <th>Escreve públicos</th>
          </tr>
          {% for role in group.roles.all %}
            <tr>
              {% if can_edit %}
                <th><a href="{% url 'groups:role' group.abbreviation role.id %}">{{ role.name }}</a></th>
              {% else %}
                <th>{{ role.name }}</th>
              {% endif %}
              {% if role.can_modify_roles or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_assign_roles or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_announce or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_read_conversations or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_write_conversations or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_read_internal_conversations or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_write_internal_conversations or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_read_internal_documents or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_write_internal_documents or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_write_public_documents or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
              {% if role.can_change_schedules or role.is_admin %}
                <td><img alt="Sim" src="{% static 'img/icons/checkbox.svg' %}"></td>
              {% else %}
                <td><img alt="Não" src="{% static 'img/icons/cross.svg' %}"></td>
              {% endif %}
            </tr>
          {% endfor %}
        </table>
      </div>
      <a class="ui-btn end" href="{% url 'groups:role' group.abbreviation 0 %}">Criar</a>
    </div>
  </div>
  <div class="pane">
    <div class="pane-title"><h2>Afiliações</h2></div>
    <div class="pane-content">
      <form class="col" method="post" action="{% url 'groups:roles' group.abbreviation %}">
        {% csrf_token %}
        {{ membership_formset.media }}
        {{ membership_formset.management_form }}
        {{ membership_formset.management_form.errors }}
        <table class="stylized grow">
          <thead>
          <th>Membro</th>
          <th>Cargo</th>
          <th>Desassociar</th>
          </thead>
          <tbody>
          {% for form in membership_formset %}
            {% if form.errors %}<tr>{{ form.errors }}</tr>{% endif %}
            <tr>
              {{ form.id }}
              {{ form.group }}
              <td>{{ form.member }}</td>
              <td>{{ form.role }}</td>
              {% if membership_formset.can_delete %}
                <td>{{ form.DELETE }}</td>
              {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
        {{ membership_formset.media }}
        <input class="ui-btn end" type="submit" value="Guardar">
      </form>
    </div>
  </div>
{% endblock %}