source/api/urls.py
from django.urls import path

from api import views

app_name = 'api'

urlpatterns = [
    path('search', views.search.search_view, name="search"),
    # College
    path('buildings', views.college.BuildingList.as_view(), name="buildings"),
    path('places', views.college.PlaceList.as_view(), name="places"),
    path('rooms', views.college.RoomList.as_view(), name="rooms"),
    path('building/<int:building_id>/', views.college.Building.as_view(), name="building"),
    path('building/<int:building_id>/rooms', views.calendar.building_schedule_rooms_view,
         name="building_schedule_rooms"),
    path('building/<int:building_id>/schedule', views.calendar.building_schedule_shifts_view, name="building_schedule"),
    path('departments', views.college.DepartmentList.as_view(), name="departments"),
    path('department/<int:department_id>/', views.college.DepartmentDetailed.as_view(), name="department"),
    path('classes', views.college.ClassList.as_view(), name="classes"),
    path('courses', views.college.CoursesList.as_view(), name="courses"),
    path('course/<int:course_id>/', views.college.CourseDetailed.as_view(), name="course"),
    path('class/<int:class_id>/', views.college.Class.as_view(), name="class"),
    path('class/i/<int:instance_id>/', views.college.ClassInstance.as_view(), name="class_instance"),
    path('class/i/<int:instance_id>/shifts', views.college.ClassInstanceShifts.as_view(),
         name="class_instance_shifts"),
    path('class/i/<int:instance_id>/files', views.college.ClassFiles.as_view(), name="class_instance_files"),
    path('class/i/<int:instance_id>/schedule', views.calendar.class_instance_schedule, name="class_instance_schedule"),
    path('shift/<int:shift_id>', views.college.Shift.as_view(), name="shift"),
    path('enrollment/<int:enrollment_id>', views.college.Enrollment.as_view(), name="enrollment"),
    path('teacher/<int:teacher_id>/', views.college.Teacher.as_view(), name="teacher"),
    path('student/<int:student_id>/', views.college.Student.as_view(), name="student"),
    path('teacher/<int:teacher_id>/schedule', views.calendar.teacher_schedule, name="teacher_schedule"),

    # Chat
    # path('chat/list', views.chat.chat_list, name='chat_list'),
    path('chat/presence', views.chat.chat_presence, name='chat_presence'),
    path('chat/query', views.chat.chat_query, name='chat_query'),
    path('chat/<int:chat_id>/info', views.chat.chat_info, name='chat_info'),
    path('chat/<str:reference>/join', views.chat.chat_join_request, name='chat_join'),
    path('chat/<int:chat_id>/history', views.chat.chat_history, name='chat_history'),
    path('chat/<int:user_id>/dmrequest', views.chat.dm_request, name='chat_dm_request'),
    # Groups
    path('groups/', views.groups.GroupList.as_view(), name="groups"),
    path('group/<int:group_id>/', views.groups.Group.as_view(), name="group_activities"),
    path('group/<str:abbr>/calendar', views.calendar.group_calendar, name='group_calendar'),
    path('group/<str:abbr>/subscribe', views.groups.GroupSubscription.as_view(), name='group_subscription'),
    path('group/<str:abbr>/membership', views.groups.GroupMembershipRequest.as_view(), name='group_membership_request'),
    # News
    path('news/', views.news.NewsList.as_view(), name="news"),
    path('news/<int:pk>/', views.news.News.as_view(), name="news_item"),
    # Services
    path('services/', views.services.ServiceList.as_view(), name="services"),
    path('bars/', views.services.BarList.as_view(), name="services_bars"),
    path('transportation/day', views.third_party.transportation_day, name="transportation_day"),
    path('transportation/next', views.third_party.transportation_upcoming, name="transportation_upcoming"),
    path('weather/', views.third_party.weather, name="weather"),
    path('weather/chart/', views.third_party.weather_chart, name="weather_chart"),
    path('boinc/', views.third_party.boinc_view, name="boinc"),
    path('boinc/users/', views.third_party.boinc_users, name="boinc_users"),
    path('boinc/projects/', views.third_party.boinc_projects, name="boinc_projects"),
    path('stars/gitlab/', views.third_party.gitlab_stars, name="gitlab_stars"),
    path('stars/github/', views.third_party.github_stars, name="github_stars"),
    # Synopses
    path('learning/areas', views.learning.Areas.as_view(), name="synopses_areas"),
    path('learning/area/<int:pk>/', views.learning.Area.as_view(), name="synopses_area"),
    path('learning/subarea/<int:pk>/', views.learning.Subarea.as_view(), name="synopses_subarea"),
    path('learning/class/<int:pk>/children/', views.learning.ClassSections.as_view(),
         name='synopses_class_section'),
    path('learning/section/<int:pk>/', views.learning.Section.as_view(), name="synopses_section"),
    path('learning/section/<int:pk>/children/', views.learning.SectionChildren.as_view(),
         name='synopses_section_children'),
    path('learning/postable/<int:pk>/votes', views.learning.PostableVotes.as_view(), name="postable_votes"),
    path('learning/question/<int:pk>/votes', views.learning.QuestionUserVotes.as_view(), name="question_votes"),
    # Users
    path('login', views.users.Login.as_view(), name="user_login"),
    path('logout', views.users.Logout.as_view(), name="user_logout"),
    path('validation', views.users.ValidateToken.as_view(), name="user_validate"),
    path('profile/<str:nickname>/', views.users.ProfileDetailed.as_view(), name="user_profile"),
    path('profile/<str:nickname>/external_pages', views.users.UserExternalPages.as_view(), name='user_external_pages'),
    path('user/<str:nickname>/current_shifts', views.college.UserShiftInstances.as_view()),
    path('user/<str:nickname>/calendar', views.calendar.user_calendar, name='user_calendar'),
    path('user/<str:nickname>/schedule', views.calendar.user_schedule, name='user_schedule'),
    path('notification/count', views.users.notification_count_view, name='notification_count'),
    path('notification/list', views.users.UserNotificationList.as_view(), name='notification_list'),
    path('moderate/<int:user_id>/', views.users.UserModeration.as_view(), name='user_moderation'),
]

source/college/urls.py
from django.urls import path

from . import views

app_name = 'college'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('campus/', views.map_view, name='campus'),
    path('campus/mapa/', views.map_view, name='map'),
    path('campus/transportes/', views.transportation_view, name='transportation'),
    path('campus/disponivel/', views.available_places_view, name='available_places'),
    path('campus/edificios/', views.buildings_view, name='buildings'),
    path('campus/edificio/<int:building_id>/', views.building_view, name='building'),
    path('campus/edificio/<int:building_id>/nova_sala', views.room_create_view, name='room_create'),
    path('sala/<int:room_id>/', views.room_view, name='room'),
    path('sala/<int:room_id>/editar', views.room_edit_view, name='room_edit'),
    path('departamentos/', views.departments_view, name='departments'),
    path('departamento/<int:department_id>/', views.department_view, name='department'),
    path('departamento/<int:department_id>/editar', views.department_edit_view, name='department_edit'),
    path('aluno/<int:student_id>', views.student_view, name='student'),
    path('professores/consentimento', views.teacher_consent_view, name='teachers_consent'),
    path('professor/<int:teacher_id>', views.teacher_view, name='teacher'),
    path('professor/<int:teacher_id>/editar', views.teacher_edit_view, name='teacher_edit'),
    path('professor/<int:teacher_id>/avaliar', views.teacher_review_create_view, name='teacher_review_create'),
    path('professor/<int:teacher_id>/avaliações', views.teacher_reviews_view, name='teacher_reviews'),
    path('cadeira/<int:class_id>/', views.class_view, name='class'),
    path('cadeira/<int:class_id>/editar', views.class_edit_view, name='class_edit'),
    path('cadeira/<int:class_id>/duvidas', views.class_questions_view, name='class_questions'),
    path('cadeira/i/<int:instance_id>/', views.class_instance_view, name='class_instance'),
    path('cadeira/i/<int:instance_id>/editar', views.class_instance_edit_view, name='class_instance_edit'),
    path('cadeira/i/<int:instance_id>/turnos', views.class_instance_shifts_view, name='class_instance_shifts'),
    path('cadeira/i/<int:instance_id>/turno/<int:shift_id>',
         views.class_instance_shift_view,
         name='class_instance_shift'),
    path('cadeira/i/<int:instance_id>/inscritos', views.class_instance_enrolled_view, name='class_instance_enrolled'),
    path('cadeira/i/<int:instance_id>/eventos', views.class_instance_events_view, name='class_instance_events'),
    path('cadeira/i/<int:instance_id>/avaliar', views.class_instance_review_create_view,
         name='class_instance_review_create'),
    path('cadeira/i/<int:instance_id>/opiniões', views.class_instance_reviews_view, name='class_instance_reviews'),
    path('cadeira/i/<int:instance_id>/ficheiros', views.class_instance_files_view, name='class_instance_files'),
    path('cadeira/i/<int:instance_id>/ficheiros/editar',
         views.class_instance_files_edit_view,
         name='class_instance_files_edit'),
    path('cadeira/i/<int:instance_id>/ficheiros/anexar',
         views.class_instance_file_attach_view,
         name='class_instance_file_attach'),
    path('cadeira/i/<int:instance_id>/ficheiros/anexar/<str:file_hash>',
         views.class_instance_file_attach_view,
         name='class_instance_new_file_attach'),
    path('cadeira/i/<int:instance_id>/ficheiro/<int:class_file_id>/editar',
         views.class_instance_file_edit_view,
         name='class_instance_file_edit'),
    path('cadeira/i/<int:instance_id>/ficheiro/<str:class_file_id>',
         views.class_instance_file_view,
         name='class_instance_file'),
    path('cadeira/i/<int:instance_id>/ficheiro/<str:class_file_id>/download',
         views.class_instance_file_download,
         name='class_instance_file_download'),
    path('ficheiro/<str:file_hash>/', views.file_view, name='file'),
    path('ficheiro/<str:file_hash>/editar', views.file_edit_view, name='file_edit'),
    path('ficheiro/<str:file_hash>/download', views.file_download, name='file_download'),
    path('ficheiro/novo/', views.file_upload_view, name='file_upload'),
    path('cursos/', views.courses_view, name='courses'),
    path('curso/<int:course_id>/', views.course_view, name='course'),
    path('curso/<int:course_id>/alunos/', views.course_students_view, name='course_students'),
    path('curso/<int:course_id>/programa/', views.course_curriculum_view, name='course_curriculum'),
    path('curso/<int:course_id>/editar', views.course_edit_view, name='course_edit'),
    path('ac/class', views.ClassAutocomplete.as_view(), name='class_ac'),
    path('ac/place', views.PlaceAutocomplete.as_view(), name='place_ac'),
    path('ac/teacher', views.TeacherAutocomplete.as_view(), name='teacher_ac'),
    path('ac/unreg_teacher', views.UnregisteredTeacherAutocomplete.as_view(), name='unreg_teacher_ac'),
    path('ac/student', views.StudentAutocomplete.as_view(), name='student_ac'),
    path('ac/unreg_student', views.UnregisteredStudentAutocomplete.as_view(), name='unreg_student_ac'),
    path('ac/file', views.FileAutocomplete.as_view(), name='file_ac'),
    path('ac/curr/component', views.CurricularComponentAutocomplete.as_view(), name='curr_component_ac'),
    path('ac/curr/class', views.CurricularClassAutocomplete.as_view(), name='curr_class_ac'),
    path('ac/curr/block', views.CurricularBlockAutocomplete.as_view(), name='curr_block_ac'),
    path('ac/curr/blockvariant', views.CurricularBlockVariantAutocomplete.as_view(), name='curr_block_variant_ac'),
]

source/learning/urls.py
from django.urls import path

from . import views

app_name = 'learning'

urlpatterns = [
    # Synopses related
    path('', views.areas_view, name='areas'),
    path('area/<int:area_id>/', views.area_view, name='area'),
    path('area/<int:area_id>/propor/', views.subarea_create_view, name='subarea_create'),
    path('subarea/<int:subarea_id>/', views.subarea_view, name='subarea'),
    path('subarea/<int:subarea_id>/editar/', views.subarea_edit_view, name='subarea_edit'),
    path('subarea/<int:subarea_id>/criar_seccao/', views.section_create_view, name='subarea_section_create'),
    path('subarea/<int:subarea_id>/seccao/<int:section_id>/', views.subarea_section_view, name='subarea_section'),
    path('seccao/<int:parent_id>/criar_subseccao/', views.section_create_view, name='subsection_create'),
    path('seccao/<int:section_id>/', views.section_view, name='section'),
    path('seccao/<int:parent_id>/subseccao/<int:child_id>/', views.subsection_view, name='subsection'),
    path('seccao/<int:section_id>/autores/', views.section_authors_view, name='section_authors'),
    path('seccao/<int:section_id>/exercicios/', views.section_exercises_view, name='section_exercises'),
    path('cadeira/<int:class_id>/', views.class_sections_view, name='class'),
    path('cadeira/<int:class_id>/seccoes/', views.class_manage_sections_view, name='class_manage'),
    path('cadeira/<int:class_id>/<int:section_id>/', views.class_section_view, name='class_section'),
    path('seccao/<int:section_id>/editar/', views.section_edit_view, name='section_edit'),
    # Exercise related
    path('exercicios', views.exercises_view, name='exercises'),
    path('exercicios/criar/', views.create_exercise_view, name='exercise_create'),
    path('exercicios/editar/<int:exercise_id>/', views.edit_exercise_view, name='exercise_edit'),
    path('exercicios/departamento/<int:department_id>/', views.department_exercises_view, name='department_exercises'),
    path('exercicio/<int:exercise_id>/', views.exercise_view, name='exercise'),
    path('exercicio/preview/', views.exercise_preview_view, name='exercise_preview'),
    # QA related
    path('duvidas', views.questions_view, name='questions'),
    path('duvida/colocar/', views.question_create_view, name='question_create'),
    path('duvida/<int:question_id>/', views.question_view, name='question'),
    path('duvida/<int:question_id>/editar', views.question_edit_view, name='question_edit'),
    path('duvida/resposta/<int:answer_id>/editar', views.answer_edit_view, name='answer_edit'),
    # Autocompletion helpers
    path('ac/area/', views.AreaAutocomplete.as_view(), name='area_ac'),
    path('ac/subarea/', views.SubareaAutocomplete.as_view(), name='subarea_ac'),
    path('ac/section/', views.SectionAutocomplete.as_view(), name='section_ac'),
    path('ac/exercise/', views.ExerciseAutocomplete.as_view(), name='exercise_ac'),
]

source/news/urls.py
from django.contrib.sitemaps import Sitemap
from django.urls import path

from news import views
from news import models as m

app_name = 'news'


class NewsSitemap(Sitemap):
    changefreq = "weekly"
    priority = 0.6

    def items(self):
        return m.NewsItem.objects.filter()

    def lastmod(self, obj):
        return obj.edit_datetime if obj.edited else obj.datetime


urlpatterns = [
    path('', views.index_view, name='index'),
    path('aviso/<str:pinned_item_id>/', views.pinned_item_view, name='pinned_item'),
    path('<str:news_item_id>/', views.item_view, name='item'),
]

source/college/templates/college/class.html
{% extends 'supernova/base.html' %}

{% load static %}

{% block content_wrapper %}
  <div class="header-decorator">
    {% if perms.college.change_class %}
      <div class="header-decorator-options">
        <ul>
          <li><a href="{% url 'college:class_edit' klass.id %}">Editar</a></li>
        </ul>
      </div>
    {% endif %}
    <div>
      <h1>{{ klass.name }}</h1>
      {% if klass.department %}
        <h3>
          <a href="{% url 'college:department' klass.department.id %}">Departamento de {{ klass.department.name }}</a>
        </h3>
      {% else %}
        <h3>Departamento desconhecido</h3>
      {% endif %}
    </div>
  </div>
  <div class="row padded">
    <div class="col big">
      <div class="pane">
        <div class="pane-title"><h2>Descrição</h2></div>
        <div class="pane-content">
          {% if klass.description %}
            {{ klass.description_html|safe }}
          {% else %}
            Sem uma descrição introduzida.
          {% endif %}
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Planos curriculares</h2></div>
        <div class="pane-content">
          Planos curriculares incompletos.
        </div>
      </div>
      <div class="row baseline">
        <div class="pane grow" style="flex-basis: 500px;">
          <div class="pane-title"><h2>Opiniões (várias edições)</h2></div>
          <div class="pane-content">
            {% include 'feedback/reviews_widget.html' %}
            {% if reviews|length == 0 %}
              Sem opiniões.
            {% endif %}
          </div>
        </div>
        <div class="pane grow" style="flex-basis: 500px;">
          <div class="pane-title"><h2><a href="{% url 'college:class_questions' klass.id %}">Dúvidas</a></h2>
          </div>
          <div class="pane-content question-list small">
            {% for obj in questions %}
              {% include 'learning/question-list-item.html' %}
              {% if not forloop.last %}
                <hr>{% endif %}
            {% endfor %}
            {% if questions|length == 0 %}
              <span class="indented">Sem dúvidas colocadas.</span>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="col nogrow">
      <div class="pane">
        <div class="pane-title"><h2>Informação</h2></div>
        <div class="pane-content">
          <h3>Abreviação</h3>
          <span class="indented">{{ klass.abbreviation }}</span>
          <h3>Departamento</h3>
          {% if klass.department %}
            <a class="indented entity" href="{% url 'college:department' klass.department.id %}">Departamento de {{ klass.department.name }}</a>
          {% else %}
            <span class="indented">Departamento desconhecido</span>
          {% endif %}
          {% if klass.url %}
            <h3>Página</h3>
            <a class="indented" href="{{ klass.url }}">Link</a>
          {% endif %}
          <h3>Créditos</h3>
          <span class="indented">{{ klass.ects }} ECTS</span>
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Edições</h2></div>
        <div class="pane-content">
          {% if perms.users.student_access %}
            <ul class="menu">
              {% for instance in instances %}
                <li>
                  <a href="{% url 'college:class_instance' instance.id %}">{{ instance.occasion }}</a>
                </li>
              {% endfor %}
            </ul>
          {% else %}
            A consulta de edições está restrita a alunos e docentes.
          {% endif %}
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Docentes <small>(entre edições)</small></h2></div>
        <div class="pane-content">
          <ul class="entity-list">
            {% for teacher in teachers %}
              <li><a href="{% url 'college:teacher' teacher.id %}">{{ teacher.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

source/college/templates/college/class_edit.html
{% extends 'supernova/base.html' %}

{% load static %}

{% block content_wrapper %}
  <div class="header-decorator">
    <div>
      <h1>{{ klass.name }}</h1>
      {% if klass.department %}
        <h3>
          <a href="{% url 'college:department' klass.department.id %}">Departamento de {{ klass.department.name }}</a>
        </h3>
      {% else %}
        <h3>Departamento desconhecido</h3>
      {% endif %}
    </div>
  </div>
  <div class="col padded">
    <div class="pane">
      <div class="pane-title"><h2>Editar unidade curricular</h2></div>
      <div class="pane-content">
        <form class="col" method="post" action="{% url 'college:class_edit' klass.id %}">
          {% csrf_token %}
          <div class="form-block">
            <h3>Informação</h3>
            <div class="form-row">
              <div class="form-row-top">
                <h4>Descrição da cadeira</h4>
              </div>
              <div>{{ form.description }}</div>
            </div>
            <div class="form-row">
              <div class="form-row-top">
                <h4>Página oficial</h4>
                {{ form.url }}
              </div>
              <div class="form-row-description">
                Página oficial desta unidade curricular nos portais da universidade.
              </div>
            </div>
          </div>
          {% include 'college/importable_edit.html' %}
          <input class="ui-btn end" type="submit" value="Gravar"/>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

source/college/templates/college/class_instance_file_edit.html
{% extends 'supernova/base.html' %}

{% load static %}

{% block content_wrapper %}
  <div class="header-decorator">
    <div class="header-decorator-options">
      <ul>
        <li><a href="{% url 'college:file_edit' form.instance.file.hash %}">Editar raiz</a></li>
      </ul>
    </div>
    <div>
      <h1>{{ instance.parent.name }}</h1>
      <h3>{{ instance.occasion }}</h3>
    </div>
  </div>
  <div class="col padded">
    <div class="pane">
      <div class="pane-title"><h2>Editar edição</h2></div>
      <div class="pane-content">
        <form class="col" method="post" action="{% url 'college:class_instance_file_edit' instance.id form.instance.id %}">
          {% csrf_token %}
          <div class="form-block">
            <h3>Informação </h3>
            <div class="form-row">
              <div class="form-row-top">
                <h4>Nome</h4>{{ form.name }}
              </div>
              <div class="form-row-description">
                O nome que o ficheiro apresenta.
              </div>
            </div>
            <div class="form-row">
              <div class="form-row-top">
                <h4>Tipo</h4>{{ form.category }}
              </div>
              <div class="form-row-description">
                A categoria em que o ficheiro se insere.
              </div>
            </div>
            <div class="form-row">
              <div class="form-row-top">
                <h4>Visibilidade</h4>{{ form.visibility }}
              </div>
              <div class="form-row-description">
                A audiência que consegue visualizar este ficheiro.
              </div>
            </div>
          </div>
          {% if form.instance.external %}
            {% include 'college/importable_edit.html' %}
          {% endif %}
          <input class="ui-btn end" type="submit" value="Gravar"/>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

source/college/templates/college/class_questions.html
{% extends 'supernova/base.html' %}

{% load static %}

{% block content_wrapper %}
  <div class="header-decorator">
    {% if perms.learning.add_question %}
      <div class="header-decorator-options">
        <ul>
          <li><a href="{% url 'learning:question_create' %}?class={{ klass.id }}">Colocar dúvida</a></li>
        </ul>
      </div>
    {% endif %}
    <div>
      <h1>{{ klass.name }}</h1>
      {% if klass.department %}
        <h3>
          <a href="{% url 'college:department' klass.department.id %}">Departamento de {{ klass.department.name }}</a>
        </h3>
      {% else %}
        <h3>Departamento desconhecido</h3>
      {% endif %}
    </div>
  </div>
  <div class="col padded">
    <div class="pane">
      <div class="pane-title"><h2>Questões</h2></div>
      <div class="pane-content question-list">
        {% for obj in questions %}
          {% include 'learning/question-list-item.html' %}
          {% if not forloop.last %}
            <hr>{% endif %}
        {% endfor %}
        {% if questions|length == 0 %}
          <span class="indented">Sem dúvidas colocadas.</span>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

source/college/templates/college/college.html
{% extends 'supernova/content_only_formatted.html' %}

{% block title %}
  <h2>Faculdade</h2>
{% endblock %}
{% block content %}
  <ul style="list-style: none; font-size: 1.2em">
    <li><a href="{% url 'college:departments' %}">Departamentos</a></li>
{#    <li><a href="{% url 'college:teachers' %}">Professores</a></li>#}
    <li><a href="{% url 'college:courses' %}">Cursos</a></li>
    <li><a href="{% url 'news:index' %}">Notícias</a></li>
    <li>Campus</li>
    <ul style="list-style: none">
      <li><a href="{% url 'college:buildings' %}">Edificios</a></li>
      <li><a href="{% url 'college:map' %}">Mapa</a></li>
      <li><a href="{% url 'college:transportation' %}">Transportes</a></li>
      <li><a href="{% url 'college:available_places' %}">Espaços disponíveis</a></li>
    </ul>
  </ul>
{% endblock %}

source/college/templates/college/course.html
{% extends 'supernova/base.html' %}

{% load static %}

{#{% block head %}#}
{#  <style>#}
{#      .curriculum .block, .curriculum .class {#}
{#          border: 1px solid var(--pane-bg-highlight);#}
{#          border-left: 2px solid var(--highlight);#}
{#      }#}
{##}
{#      .curriculum .class {#}
{#          display: flex;#}
{#      }#}
{##}
{#      .curriculum .class h4, .curriculum .block h4 {#}
{#          display: inline-block;#}
{#          flex-grow: 1;#}
{#          margin-left: 5px;#}
{#      }#}
{##}
{#      .attrs {#}
{#          display: flex;#}
{#          white-space: nowrap;#}
{#      }#}
{##}
{#      .attrs div {#}
{#          display: flex;#}
{#          flex-direction: column;#}
{#          align-items: center;#}
{#          padding: 5px;#}
{#          background-color: var(--input-light);#}
{#          border-left: 1px solid var(--primary4),#}
{#      }#}
{##}
{#      .attrs .val {#}
{#          font-weight: bold;#}
{#      }#}
{#  </style>#}
{#{% endblock %}#}

{% block content_wrapper %}
  <div class="header-decorator">
    {% if perms.college.change_course %}
      <div class="header-decorator-options">
        <ul>
          <li><a href="{% url 'college:course_edit' course.id %}">Editar</a></li>
        </ul>
      </div>
    {% endif %}
    <div>
      <h1>{{ course }}</h1>
      {% if course.department is None %}
        <h3>Sem departamento associado</h3>
      {% else %}
        <h3>
          <a href="{% url 'college:department' course.department.id %}">Departamento de {{ course.department }}</a>
        </h3>
      {% endif %}
    </div>
  </div>
  <div class="row nowrap padded">
    <div class="col">
      <div class="pane">
        <div class="pane-title"><h2>Descrição</h2></div>
        <div class="pane-content">
          <p>
            {% if course.description %}
              {{ course.description_html | safe }}
            {% else %}
              Sem descrição.
            {% endif %}
          </p>
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Estrutura Curricular</h2></div>
        <div class="pane-content curriculum">
          {% if curriculum %}
            {% with level=curriculum.aggregation  %}
              {% for child in level.children %}
                {% with child as level %}
                  {% include 'college/curriculum_level.html' %}
                {% endwith %}
              {% endfor %}
            {% endwith %}
          {% else %}
            <p>Estrutura curricular por definir.</p>
          {% endif %}
          <p>
            Nota: Definir a estrutura curricular de um curso é trabalhoso (+- 3/4 horas para MIEI ou MIEEC) e
            impossível de fazer de forma garantidamente correta sem colaboração (dado que quer o CLIP como as restantes páginas da UNL tem erros).
            Se pertences a um dos cursos sem estutura definida e compreendes o funcionamento do curso, agradecemos a tua ajuda, fala connosco!
          </p>
        </div>
      </div>
    </div>
    <div class="col nogrow noshrink">
      <div class="pane">
        <div class="pane-title"><h2>Navegação</h2></div>
        <div class="pane-content">
          <ul class="menu">
{#            <li><a class="disabled" href="{% url 'college:course_curriculum' course.id %}">Programa curricular</a>#}
            </li>
            <li><a href="{% url 'college:course_students' course.id %}">Alunos</a></li>
            <li><span class="disabled">Núcleo do curso</span></li>
            <li><span class="disabled">Concelho pedagógico</span></li>
          </ul>
        </div>
      </div>
      <div class="pane">
        <div class="pane-title"><h2>Informação</h2></div>
        <div class="pane-content">
          <h3>Total alunos</h3>
          <span class="indented">{{ student_count }}</span>
          <h3>Alunos ativos</h3>
          <span class="indented">{{ active_student_count }}</span>
          <h3>Novos alunos</h3>
          <span class="indented">{{ new_students_count }}</span>
          {# <h3>Média dos alunos:</h3>#}
          {# <span class="info-entry">TODO</span>#}
          {# <h3>Taxa de desistências:</h3>#}
          {# <span class="info-entry">TODO</span>#}
        </div>
      </div>
    </div>
  </div>
  <script>
    function showChildren(e){
        e.querySelector('.indented').style.display = 'block';
    }
  </script>
{% endblock %}