source/api/urls.py
from django.urls import path

from api import views

app_name = 'api'

urlpatterns = [
    path('search', views.search.search_view, name="search"),
    # College
    path('buildings', views.college.BuildingList.as_view(), name="buildings"),
    path('places', views.college.PlaceList.as_view(), name="places"),
    path('rooms', views.college.RoomList.as_view(), name="rooms"),
    path('building/<int:building_id>/', views.college.Building.as_view(), name="building"),
    path('building/<int:building_id>/rooms', views.calendar.building_schedule_rooms_view,
         name="building_schedule_rooms"),
    path('building/<int:building_id>/schedule', views.calendar.building_schedule_shifts_view, name="building_schedule"),
    path('departments', views.college.DepartmentList.as_view(), name="departments"),
    path('department/<int:department_id>/', views.college.DepartmentDetailed.as_view(), name="department"),
    path('classes', views.college.ClassList.as_view(), name="classes"),
    path('courses', views.college.CoursesList.as_view(), name="courses"),
    path('course/<int:course_id>/', views.college.CourseDetailed.as_view(), name="course"),
    path('class/<int:class_id>/', views.college.Class.as_view(), name="class"),
    path('class/i/<int:instance_id>/', views.college.ClassInstance.as_view(), name="class_instance"),
    path('class/i/<int:instance_id>/shifts', views.college.ClassInstanceShifts.as_view(),
         name="class_instance_shifts"),
    path('class/i/<int:instance_id>/files', views.college.ClassFiles.as_view(), name="class_instance_files"),
    path('class/i/<int:instance_id>/schedule', views.calendar.class_instance_schedule, name="class_instance_schedule"),
    path('shift/<int:shift_id>', views.college.Shift.as_view(), name="shift"),
    path('enrollment/<int:enrollment_id>', views.college.Enrollment.as_view(), name="enrollment"),
    path('teacher/<int:teacher_id>/', views.college.Teacher.as_view(), name="teacher"),
    path('student/<int:student_id>/', views.college.Student.as_view(), name="student"),
    path('teacher/<int:teacher_id>/schedule', views.calendar.teacher_schedule, name="teacher_schedule"),

    # Chat
    # path('chat/list', views.chat.chat_list, name='chat_list'),
    path('chat/presence', views.chat.chat_presence, name='chat_presence'),
    path('chat/query', views.chat.chat_query, name='chat_query'),
    path('chat/<int:chat_id>/info', views.chat.chat_info, name='chat_info'),
    path('chat/<str:reference>/join', views.chat.chat_join_request, name='chat_join'),
    path('chat/<int:chat_id>/history', views.chat.chat_history, name='chat_history'),
    path('chat/<int:user_id>/dmrequest', views.chat.dm_request, name='chat_dm_request'),
    # Groups
    path('groups/', views.groups.GroupList.as_view(), name="groups"),
    path('group/<int:group_id>/', views.groups.Group.as_view(), name="group_activities"),
    path('group/<str:abbr>/calendar', views.calendar.group_calendar, name='group_calendar'),
    path('group/<str:abbr>/subscribe', views.groups.GroupSubscription.as_view(), name='group_subscription'),
    path('group/<str:abbr>/membership', views.groups.GroupMembershipRequest.as_view(), name='group_membership_request'),
    # News
    path('news/', views.news.NewsList.as_view(), name="news"),
    path('news/<int:pk>/', views.news.News.as_view(), name="news_item"),
    # Services
    path('services/', views.services.ServiceList.as_view(), name="services"),
    path('bars/', views.services.BarList.as_view(), name="services_bars"),
    path('transportation/day', views.third_party.transportation_day, name="transportation_day"),
    path('transportation/next', views.third_party.transportation_upcoming, name="transportation_upcoming"),
    path('weather/', views.third_party.weather, name="weather"),
    path('weather/chart/', views.third_party.weather_chart, name="weather_chart"),
    path('boinc/', views.third_party.boinc_view, name="boinc"),
    path('boinc/users/', views.third_party.boinc_users, name="boinc_users"),
    path('boinc/projects/', views.third_party.boinc_projects, name="boinc_projects"),
    path('stars/gitlab/', views.third_party.gitlab_stars, name="gitlab_stars"),
    path('stars/github/', views.third_party.github_stars, name="github_stars"),
    # Synopses
    path('learning/areas', views.learning.Areas.as_view(), name="synopses_areas"),
    path('learning/area/<int:pk>/', views.learning.Area.as_view(), name="synopses_area"),
    path('learning/subarea/<int:pk>/', views.learning.Subarea.as_view(), name="synopses_subarea"),
    path('learning/class/<int:pk>/children/', views.learning.ClassSections.as_view(),
         name='synopses_class_section'),
    path('learning/section/<int:pk>/', views.learning.Section.as_view(), name="synopses_section"),
    path('learning/section/<int:pk>/children/', views.learning.SectionChildren.as_view(),
         name='synopses_section_children'),
    path('learning/postable/<int:pk>/votes', views.learning.PostableVotes.as_view(), name="postable_votes"),
    path('learning/question/<int:pk>/votes', views.learning.QuestionUserVotes.as_view(), name="question_votes"),
    # Users
    path('login', views.users.Login.as_view(), name="user_login"),
    path('logout', views.users.Logout.as_view(), name="user_logout"),
    path('validation', views.users.ValidateToken.as_view(), name="user_validate"),
    path('profile/<str:nickname>/', views.users.ProfileDetailed.as_view(), name="user_profile"),
    path('profile/<str:nickname>/external_pages', views.users.UserExternalPages.as_view(), name='user_external_pages'),
    path('user/<str:nickname>/current_shifts', views.college.UserShiftInstances.as_view()),
    path('user/<str:nickname>/calendar', views.calendar.user_calendar, name='user_calendar'),
    path('user/<str:nickname>/schedule', views.calendar.user_schedule, name='user_schedule'),
    path('notification/count', views.users.notification_count_view, name='notification_count'),
    path('notification/list', views.users.UserNotificationList.as_view(), name='notification_list'),
    path('moderate/<int:user_id>/', views.users.UserModeration.as_view(), name='user_moderation'),
]

source/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('mensagens/', views.messages_view, name='messages'),
    path('sala/<str:room_name>/', views.room_view, name='room'),
]

source/groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('nucleos', views.nuclei_view, name='nuclei'),
    path('institucionais', views.institutional_view, name='institutional'),
    path('pedagogicos', views.pedagogic_view, name='pedagogic'),
    path('comunidades', views.communities_view, name='communities'),
    path('<str:group_abbr>', views.group_view, name='group'),
    path('<str:group_abbr>/documentos', views.documents_view, name='documents'),
    path('<str:group_abbr>/anuncios', views.announcements_view, name='announcements'),
    path('<str:group_abbr>/membros', views.members_view, name='members'),
    path('<str:group_abbr>/admissao', views.group_membership_request_view, name='membership_req'),
    path('<str:group_abbr>/candidaturas', views.group_candidates_view, name='candidates'),
    path('<str:group_abbr>/definicoes', views.settings_view, name='settings'),
    path('<str:group_abbr>/cargos', views.roles_view, name='roles'),
    path('<str:group_abbr>/cargo/<int:role_id>', views.role_view, name='role'),
    path('<str:group_abbr>/anunciar', views.announce_view, name='announce'),
    path('<str:group_abbr>/anuncio/<str:announcement_id>', views.announcement_view, name='announcement'),
    path('<str:group_abbr>/agendar', views.calendar_management_view, name='calendar_manage'),
    path('<str:group_abbr>/conversas', views.conversations_view, name='conversations'),
    path('<str:group_abbr>/conversas/criar', views.conversation_create_view, name='conversation_create'),
    path('<str:group_abbr>/conversas/<str:conversation_id>', views.conversation_view, name='conversation'),
    path('ac/group_role', views.GroupRolesAutocomplete.as_view(), name='group_role_ac'),
]

source/news/urls.py
from django.contrib.sitemaps import Sitemap
from django.urls import path

from news import views
from news import models as m

app_name = 'news'


class NewsSitemap(Sitemap):
    changefreq = "weekly"
    priority = 0.6

    def items(self):
        return m.NewsItem.objects.filter()

    def lastmod(self, obj):
        return obj.edit_datetime if obj.edited else obj.datetime


urlpatterns = [
    path('', views.index_view, name='index'),
    path('aviso/<str:pinned_item_id>/', views.pinned_item_view, name='pinned_item'),
    path('<str:news_item_id>/', views.item_view, name='item'),
]

source/supernova/urls.py
import debug_toolbar
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin, sitemaps
from django.contrib.flatpages import views as flatpages
from django.contrib.sitemaps import views as sitemaps_views
from django.views.decorators.cache import cache_page
from django.urls import path, include, reverse
from django.conf import settings

import users.views as users
import documents.views as documents
from news.urls import NewsSitemap
from . import views

app_name = 'supernova'
handler400 = views.bad_request_view
handler403 = views.permission_denied_view
handler404 = views.page_not_found_view
handler500 = views.error_view


class StaticViewSitemap(sitemaps.Sitemap):
    priority = 0.5
    changefreq = 'daily'

    def items(self):
        return ['index', 'about', 'privacy', 'faq', 'terms']

    def location(self, item):
        return reverse(item)


sitemaps = {
    'static': StaticViewSitemap,
    'news': NewsSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    # Generic views
    path('', views.index, name='index'),
    path('alterações', views.changelog_view, name='changelog'),
    path('apoio', views.support_view, name='support'),
    # College views
    path('faculdade/', include('college.urls')),
    # Services views
    path('servicos/', include('services.urls')),
    # User views
    path('u/', include('users.urls')),
    path('criar/', users.registration_view, name='registration'),
    path('confirmar/', users.registration_validation_view, name='registration_validation'),
    path('entrar/', users.login_view, name='login'),
    path('sair/', users.logout_view, name='logout'),
    # Group views
    path('grupos/', include('groups.urls')),
    # Feedback views
    path('feedback/', include('feedback.urls')),
    # Documents views
    path('documento/<int:document_id>/', documents.document, name='document'),
    # News views
    path('noticias/', include('news.urls')),
    # Learning views
    path('estudo/', include('learning.urls')),
    # Chat views
    path('chat/', include('chat.urls')),
    # Management view
    path('manage/', include('management.urls')),
    # path('loja/', include('store.urls')),
    # REST API views
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # Utils
    url(r'^captcha/', include('captcha.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    path('sobre/', flatpages.flatpage, {'url': '/sobre/'}, name='about'),
    path('privacidade/', flatpages.flatpage, {'url': '/privacidade/'}, name='privacy'),
    path('faq/', flatpages.flatpage, {'url': '/faq/'}, name='faq'),
    path('termos/', flatpages.flatpage, {'url': '/termos/'}, name='terms'),
    path('intro/', flatpages.flatpage, {'url': '/intro/'}, name='intro'),
    url('', include('pwa.urls')),
    path('sitemap.xml',
         cache_page(86400)(sitemaps_views.index),
         {'sitemaps': sitemaps}),
    path('sitemap-<section>.xml',
         cache_page(86400)(sitemaps_views.sitemap), {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

source/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('<str:nickname>/', views.profile_view, name='profile'),
    path('<str:nickname>/horario/', views.user_schedule_view, name='schedule'),
    path('<str:nickname>/calendario/', views.user_calendar_view, name='calendar'),
    path('<str:nickname>/calendario/editar', views.user_calendar_management_view, name='calendar_manage'),
    path('<str:nickname>/reputacao/', views.user_reputation_view, name='reputation'),
    path('<str:nickname>/avaliações/', views.user_evaluations_view, name='evaluations'),
    path('<str:nickname>/definicoes/', views.user_profile_settings_view, name='settings'),
    path('<str:nickname>/convites/', views.invites_view, name='invites'),
    path('<str:nickname>/convites/novo', views.create_invite_view, name='create_invite'),
    path('notificacoes', views.notifications_view, name='notifications'),
    path('ac/nickname/', views.NicknameAutocomplete.as_view(), name='nickname_ac'),
]

source/supernova/models.py
from django.db import models as djm
from django.urls import reverse
from django.conf import settings

from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from users.models import Notification


class Catchphrase(djm.Model):
    """A generic slogan that is shown beneath the title."""
    #: The presented phrase
    phrase = djm.TextField(max_length=100)

    def __str__(self):
        return self.phrase


class Changelog(djm.Model):
    """A verbose list of changes since the past major version"""
    #: The entry title
    title = djm.CharField(max_length=100)
    #: The entry content
    content = MarkdownxField()
    #: Publish date
    date = djm.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

    @property
    def content_html(self):
        return markdownify(self.content)


class ChangelogNotification(Notification):
    """A notification about a new changelog entry"""
    #: The notification associated with a :py:class:`Changelog`
    entry = djm.ForeignKey(Changelog, on_delete=djm.CASCADE)

    def to_api(self):
        result = super(ChangelogNotification, self).to_api()
        result['message'] = f'Nova versão do Supernova: {self.entry.title}'
        result['url'] = reverse('changelog')
        result['type'] = 'Alteração'
        return result

    def to_url(self):
        return reverse('changelog')

    def __str__(self):
        return f'Nova versão do Supernova: {self.entry.title}'


class SupportPledge(djm.Model):
    INDEPENDENT = 0
    INDEPENDENT_SUPPORTED = 1
    ASSOCIATION_COMPLEMENT = 2
    ASSOCIATION_REPLACEMENT = 3
    CHOICES = [
        (INDEPENDENT, 'Independente'),
        (INDEPENDENT_SUPPORTED, 'Independente com suporte'),
        (ASSOCIATION_COMPLEMENT, 'Associado em complemento'),
        (ASSOCIATION_REPLACEMENT, 'Associado para substituição'),
    ]
    user = djm.OneToOneField(settings.AUTH_USER_MODEL, on_delete=djm.CASCADE, related_name='pledge')
    pledge_towards = djm.IntegerField(choices=CHOICES)
    anonymous = djm.BooleanField(default=False)
    comment = djm.TextField(null=True, blank=True)

source/supernova/forms.py
from django import forms as djf
from supernova import models as m
from supernova.widgets import SliderInput


class SupportPledgeForm(djf.ModelForm):
    class Meta:
        model = m.SupportPledge
        fields = ('pledge_towards', 'anonymous', 'comment')
        widgets = {
            'pledge_towards': djf.RadioSelect(),
            'anonymous': SliderInput(),
        }

source/supernova/templates/supernova/menu.html
{% load static %}
{% load strutils %}

{% spaceless %}
  <div class="user lowres">
      {% if user.is_authenticated %}
            {% if user.picture %}
              <span class="pic" style="background-image: url('{{ user.picture_thumbnail.url }}')"></span>
            {% else %}
              <span class="pic"></span>
        {% endif %}
      <a class="name" href="{% url 'users:profile' user.nickname %}">
        {{ user.nickname }}
      </a>
      <a class="logout" href="{% url 'logout' %}?next={{ request.get_full_path }}">
        <img src="{% static 'img/icons/logout.svg' %}">
      </a>
    {% else %}
      <span class="pic"></span>
      <a class="name">Não autenticado</a>
      <a class="login" href="{% url 'login' %}?next={{ request.get_full_path }}">
        <img src="{% static 'img/icons/login.svg' %}">
      </a>
    {% endif %}
  </div>
  <ul>
    {% if user.is_staff %}
      <li {% if pcode|startswith:'manag' %}{% else %}class="collapse"{% endif %}>
        <input type="checkbox" id="m0"/><label for="m0">Administração</label>
        <ul>
          <li {% if pcode == 'manag_index' %}class="active"{% endif %}><a href="{% url 'management:index' %}">Painel geral</a></li>
          <li {% if pcode == 'manag_users' %}class="active"{% endif %}><a href="{% url 'management:users' %}">Utilizadores</a></li>
          <li {% if pcode == 'manag_announcements' %}class="active"{% endif %}><a href="{% url 'management:announcements' %}">Anúncios</a></li>
          <li {% if pcode == 'manag_activity' %}class="active"{% endif %}><a href="{% url 'management:activity' %}">Actividade</a></li>
          <li {% if pcode == 'manag_settings' %}class="active"{% endif %}><a href="{% url 'management:settings' %}">Definições</a></li>
        </ul>
      </li>
    {% endif %}
    {% if user.is_authenticated %}
      {% url 'users:profile' user.nickname as profile %}
      {% url 'users:schedule' user.nickname as schedule %}
      {% url 'users:calendar' user.nickname as calendar %}
      {% url 'users:evaluations' user.nickname as evaluations %}
      {% url 'users:reputation' user.nickname as reputation %}
      {% url 'chat:messages' as messages %}
      {% url 'users:settings' user.nickname as settings %}
      {% if pcode|startswith:'u' %}
        <li>
          <label for="m1">Minha conta</label>
          <ul>
            <li {% if pcode == 'u_profile' %}class="active"{% endif %}><a href="{{ profile }}">Perfil</a></li>
            <li {% if pcode == 'u_schedule' %}class="active"{% endif %}><a href="{{ schedule }}">Horário</a></li>
            {% if user.course %}<li><a href="{% url 'college:course' user.course.id %}">Curso</a></li>{% endif %}
            <li {% if pcode == 'u_evaluations' %}class="active"{% endif %}><a href="{{ evaluations }}">Avaliações</a></li>
            <li {% if pcode|startswith:'u_calendar' %}class="active"{% endif %}><a href="{{ calendar }}">Calendário</a></li>
            <li {% if pcode == 'u_chat' %}class="active"{% endif %}><a href="{{ messages }}">Mensagens</a></li>
            <li {% if pcode == 'u_reputation' %}class="active"{% endif %}><a href="{{ reputation }}">Reputação</a></li>
            <li {% if pcode == 'u_settings' %}class="active"{% endif %}><a href="{{ settings }}">Definições</a></li>
          </ul>
        </li>
      {% else %}
        <li class="collapse">
          <input type="checkbox" id="m1"/><label for="m1">Minha conta</label>
          <ul>
            <li><a href="{{ profile }}">Perfil</a></li>
            <li><a href="{{ schedule }}">Horário</a></li>
            {% if user.course %}<li><a href="{% url 'college:course' user.course.id %}">Curso</a></li>{% endif %}
            <li><a href="{{ evaluations }}">Avaliações</a></li>
            <li><a href="{{ calendar }}">Calendário</a></li>
            <li><a href="{{ messages }}">Mensagens</a></li>
            <li><a href="{{ reputation }}">Reputação</a></li>
            <li><a href="{{ settings }}">Definições</a></li>
          </ul>
        </li>
      {% endif %}
    {% endif %}

{#    {% url 'intro' as intro %}#}
    {% url 'college:courses' as courses %}
    {% url 'college:departments' as departments %}
    {% url 'college:index' as college %}
    {% url 'college:campus' as campus %}
    {% url 'college:transportation' as transportation %}
    {% url 'college:buildings' as buildings %}
{#    {% url 'college:available_places' as places %}#}
    {% url 'college:map' as map %}
    {% url 'services:services' as services %}
    {% url 'news:index' as news %}
    {% url 'feedback:index' as suggestions %}
    {% if pcode|startswith:'c' %}
      <li>
        <label>Faculdade</label>
        <ul>
{#          <li><a href="{{ intro }}">Introdução</a></li>#}
          <li {% if pcode|startswith:'c_course' %}class="active"{% endif %}><a href="{{ courses }}">Cursos</a></li>
          <li {% if pcode|startswith:'c_department' %}class="active"{% endif %}><a href="{{ departments }}">Departamentos</a></li>
          {% if pcode|startswith:'c_campus' %}
            <li>
              <label>Campus</label>
              <ul>
                <li {% if pcode|startswith:'c_campus_service' %}class="active"{% endif %}><a href="{{ services }}">Serviços</a></li>
                <li {% if pcode == 'c_campus_map' %}class="active"{% endif %}><a href="{{ map }}">Mapa</a></li>
                <li {% if pcode == 'c_campus_tranportation' %}class="active"{% endif %}><a href="{{ transportation }}">Transportes</a></li>
                <li {% if pcode|startswith:'c_campus_building' %}class="active"{% endif %}><a href="{% url 'college:buildings' %}">Edifícios</a></li>
{#                <li {% if pcode == 'c_campus_places' %}class="active"{% endif %}><a href="{{ places }}">Espaços</a></li>#}
              </ul>
            </li>
            {% else %}{# Submenu is inactive #}
            <li class="collapse">
              <input type="checkbox" id="m21"/><label for="m21">Campus</label>
              <ul>
                <li><a href="{{ services }}">Serviços</a></li>
                <li><a href="{{ map }}">Mapa</a></li>
                <li><a href="{{ transportation }}">Transportes</a></li>
                <li><a href="{{ buildings }}">Edifícios</a></li>
{#                <li><a href="{{ places }}">Espaços</a></li>#}
              </ul>
            </li>
          {% endif %}
          <li {% if pcode|startswith:'c_news' %}class="active"{% endif %}><a href="{{ news }}">Noticias</a></li>
{#          <li class="collapse disabled">#}
{#            <input type="checkbox" id="m22"/><label for="m22"><a class="disabled" href="#">Eventos</a></label>#}
{#            <ul>#}
{#              <li><a href="#">Palestras</a></li>#}
{#              <li><a href="#">Workshops</a></li>#}
{#              <li><a href="#">Festas</a></li>#}
{#              <li><a href="#">Competições</a></li>#}
{#            </ul>#}
{#          </li>#}
          {# TODO <li class="disabled"><a href="#">Perdidos</a></li>#}
          <li {% if pcode|startswith:'c_feedback' %}class="active"{% endif %}><a href="{{ suggestions }}">Sugestões</a></li>
        </ul>
      </li>
    {% else %}
      <li class="collapse">
        <input type="checkbox" id="m2"/><label for="m2">Faculdade</label>
        <ul>
{#          <li><a href="{{ intro }}">Introdução</a></li>#}
          <li><a href="{{ courses }}">Cursos</a></li>
          <li><a href="{{ departments }}">Departamentos</a></li>
          <li class="collapse">
            <input type="checkbox" id="m21"/><label for="m21">Campus</label>
            <ul>
              <li><a href="{{ services }}">Serviços</a></li>
              <li><a href="{{ map }}">Mapa</a></li>
              <li><a href="{{ transportation }}">Transportes</a></li>
              <li><a href="{{ buildings }}">Edifícios</a></li>
{#              <li><a href="{{ places }}">Espaços</a></li>#}
            </ul>
          </li>
          <li><a href="{{ news }}">Noticias</a></li>
{#          <li class="collapse disabled">#}
{#            <input type="checkbox" id="m22"/><label for="m22"><a class="disabled" href="#">Eventos</a></label>#}
{#            <ul>#}
{#              <li class="disabled"><a href="#">Palestras</a></li>#}
{#              <li><a href="#">Workshops</a></li>#}
{#              <li><a href="#">Festas</a></li>#}
{#              <li><a href="#">Competições</a></li>#}
{#            </ul>#}
{#          </li>#}
          {# TODO <li class="disabled"><a href="#">Perdidos</a></li>#}
          <li><a href="{{ suggestions }}">Sugestões</a></li>
        </ul>
      </li>
    {% endif %}

    {% url 'groups:institutional' as groups_institutional %}
    {% url 'groups:nuclei'  as groups_nuclei %}
    {% url 'groups:pedagogic' as groups_pedagogic %}
    {% url 'groups:communities' as groups_communities %}
    <li {% if not pcode|startswith:'g' %}class="collapse"{% endif %}>
      <input type="checkbox" id="m5"/><label for="m5">Entidades</label>
      <ul>
        <li {% if pcode|startswith:'g_inst' %}class="active"{% endif %}><a href="{{ groups_institutional }}">Institucionais</a></li>
        <li {% if pcode|startswith:'g_nucl' %}class="active"{% endif %}><a href="{{ groups_nuclei }}">Núcleos</a></li>
        <li {% if pcode|startswith:'g_ped' %}class="active"{% endif %}><a href="{{ groups_pedagogic }}">Pedagógicos</a></li>
        <li {% if pcode|startswith:'g_com' %}class="active"{% endif %}><a href="{{ groups_communities }}">Comunidades</a></li>
      </ul>
    </li>

    {% url 'learning:areas' as synopses %}
    {% url 'learning:exercises' as exercises %}
    {% url 'learning:questions' as questions %}
    <li {% if not pcode|startswith:'l' %}class="collapse"{% endif %}>
      <input type="checkbox" id="m3"/><label for="m3">Estudo</label>
      <ul>
        <li {% if pcode|startswith:'l_synops' %}class="active"{% endif %}><a href="{{ synopses }}">Sínteses</a></li>
        <li {% if pcode|startswith:'l_exercise' %}class="active"{% endif %}><a href="{{ exercises }}">Exercícios</a></li>
        <li {% if pcode|startswith:'l_question' %}class="active"{% endif %}><a href="{{ questions }}">Dúvidas</a></li>
      </ul>
    </li>

    {% url 'about' as about %}
    {% url 'faq' as faq %}
    {% url 'privacy' as privacy %}
    {% url 'terms' as terms %}
    {% url 'support' as support %}
    <li {% if request.path != about and request.path != faq and request.path != terms and request.path != privacy %}class="collapse"{% endif %}>
      <input type="checkbox" id="m4"/><label for="m4">Supernova</label>
      <ul>
        <li {% if request.path == about %}class="active"{% endif %}><a href="{{ about }}">Sobre</a></li>
        <li {% if request.path == faq %}class="active"{% endif %}><a href="{{ faq }}">Perguntas frequentes</a></li>
        <li {% if request.path == terms %}class="active"{% endif %}><a href="{{ terms }}">Termos de utilização</a></li>
        <li {% if request.path == privacy %}class="active"{% endif %}><a href="{{ privacy }}">Politica de privacidade</a></li>
        <li {% if request.path == support %}class="active"{% endif %}><a href="{{ support }}">Apoia-nos!</a></li>
{#        <li><a href="https://gitlab.com/claudiop/Supernova">Biforca-me</a></li>#}
      </ul>
    </li>
  </ul>
  <div id="nav-end" class="midhighres">
    <div class="tiny-btn-widget">
      <a class="tiny-btn" href="https://gitlab.com/claudiop/Supernova" target="_blank" rel="noopener">
        <img alt="gitlab" src="{% static 'img/third-party/gitlab.svg' %}">
        <span> ★</span>
      </a>
      <a id="gitlab-count" class="star-count" href="https://gitlab.com/claudiop/Supernova/-/starrers" target="_blank" rel="noopener">?</a>
    </div>
    <div class="tiny-btn-widget">
      <a class="tiny-btn" href="https://github.com/claudioap/Supernova" target="_blank" rel="noopener">
        <img alt="github" src="{% static 'img/third-party/github_white.svg' %}">
        <span> ★</span>
      </a>
      <a id="github-count" class="star-count" href="https://github.com/claudioap/Supernova/stargazers" target="_blank" rel="noopener">?</a>
    </div>
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.pt"><img id="license-img" src="{% static 'img/ccsabync.svg' %}"></a>
  </div>
{% endspaceless %}